// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.int.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnSignInReq struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ConnAddr             string   `protobuf:"bytes,4,opt,name=conn_addr,json=connAddr,proto3" json:"conn_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnSignInReq) Reset()         { *m = ConnSignInReq{} }
func (m *ConnSignInReq) String() string { return proto.CompactTextString(m) }
func (*ConnSignInReq) ProtoMessage()    {}
func (*ConnSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{0}
}

func (m *ConnSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnSignInReq.Unmarshal(m, b)
}
func (m *ConnSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnSignInReq.Marshal(b, m, deterministic)
}
func (m *ConnSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnSignInReq.Merge(m, src)
}
func (m *ConnSignInReq) XXX_Size() int {
	return xxx_messageInfo_ConnSignInReq.Size(m)
}
func (m *ConnSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnSignInReq proto.InternalMessageInfo

func (m *ConnSignInReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *ConnSignInReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ConnSignInReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConnSignInReq) GetConnAddr() string {
	if m != nil {
		return m.ConnAddr
	}
	return ""
}

type ConnSignInResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnSignInResp) Reset()         { *m = ConnSignInResp{} }
func (m *ConnSignInResp) String() string { return proto.CompactTextString(m) }
func (*ConnSignInResp) ProtoMessage()    {}
func (*ConnSignInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{1}
}

func (m *ConnSignInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnSignInResp.Unmarshal(m, b)
}
func (m *ConnSignInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnSignInResp.Marshal(b, m, deterministic)
}
func (m *ConnSignInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnSignInResp.Merge(m, src)
}
func (m *ConnSignInResp) XXX_Size() int {
	return xxx_messageInfo_ConnSignInResp.Size(m)
}
func (m *ConnSignInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnSignInResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnSignInResp proto.InternalMessageInfo

type SyncReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Seq                  int64    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncReq) Reset()         { *m = SyncReq{} }
func (m *SyncReq) String() string { return proto.CompactTextString(m) }
func (*SyncReq) ProtoMessage()    {}
func (*SyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{2}
}

func (m *SyncReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncReq.Unmarshal(m, b)
}
func (m *SyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncReq.Marshal(b, m, deterministic)
}
func (m *SyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReq.Merge(m, src)
}
func (m *SyncReq) XXX_Size() int {
	return xxx_messageInfo_SyncReq.Size(m)
}
func (m *SyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReq proto.InternalMessageInfo

func (m *SyncReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SyncReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SyncReq) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type SyncResp struct {
	Messages             []*MessageItem `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SyncResp) Reset()         { *m = SyncResp{} }
func (m *SyncResp) String() string { return proto.CompactTextString(m) }
func (*SyncResp) ProtoMessage()    {}
func (*SyncResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{3}
}

func (m *SyncResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResp.Unmarshal(m, b)
}
func (m *SyncResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResp.Marshal(b, m, deterministic)
}
func (m *SyncResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResp.Merge(m, src)
}
func (m *SyncResp) XXX_Size() int {
	return xxx_messageInfo_SyncResp.Size(m)
}
func (m *SyncResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResp proto.InternalMessageInfo

func (m *SyncResp) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

type MessageACKReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceAck            int64    `protobuf:"varint,3,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,4,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACKReq) Reset()         { *m = MessageACKReq{} }
func (m *MessageACKReq) String() string { return proto.CompactTextString(m) }
func (*MessageACKReq) ProtoMessage()    {}
func (*MessageACKReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{4}
}

func (m *MessageACKReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACKReq.Unmarshal(m, b)
}
func (m *MessageACKReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACKReq.Marshal(b, m, deterministic)
}
func (m *MessageACKReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACKReq.Merge(m, src)
}
func (m *MessageACKReq) XXX_Size() int {
	return xxx_messageInfo_MessageACKReq.Size(m)
}
func (m *MessageACKReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACKReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACKReq proto.InternalMessageInfo

func (m *MessageACKReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageACKReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *MessageACKReq) GetDeviceAck() int64 {
	if m != nil {
		return m.DeviceAck
	}
	return 0
}

func (m *MessageACKReq) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

type MessageACKResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACKResp) Reset()         { *m = MessageACKResp{} }
func (m *MessageACKResp) String() string { return proto.CompactTextString(m) }
func (*MessageACKResp) ProtoMessage()    {}
func (*MessageACKResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{5}
}

func (m *MessageACKResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACKResp.Unmarshal(m, b)
}
func (m *MessageACKResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACKResp.Marshal(b, m, deterministic)
}
func (m *MessageACKResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACKResp.Merge(m, src)
}
func (m *MessageACKResp) XXX_Size() int {
	return xxx_messageInfo_MessageACKResp.Size(m)
}
func (m *MessageACKResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACKResp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACKResp proto.InternalMessageInfo

type OfflineReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineReq) Reset()         { *m = OfflineReq{} }
func (m *OfflineReq) String() string { return proto.CompactTextString(m) }
func (*OfflineReq) ProtoMessage()    {}
func (*OfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{6}
}

func (m *OfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineReq.Unmarshal(m, b)
}
func (m *OfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineReq.Marshal(b, m, deterministic)
}
func (m *OfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineReq.Merge(m, src)
}
func (m *OfflineReq) XXX_Size() int {
	return xxx_messageInfo_OfflineReq.Size(m)
}
func (m *OfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineReq proto.InternalMessageInfo

func (m *OfflineReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OfflineReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type OfflineResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineResp) Reset()         { *m = OfflineResp{} }
func (m *OfflineResp) String() string { return proto.CompactTextString(m) }
func (*OfflineResp) ProtoMessage()    {}
func (*OfflineResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{7}
}

func (m *OfflineResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineResp.Unmarshal(m, b)
}
func (m *OfflineResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineResp.Marshal(b, m, deterministic)
}
func (m *OfflineResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineResp.Merge(m, src)
}
func (m *OfflineResp) XXX_Size() int {
	return xxx_messageInfo_OfflineResp.Size(m)
}
func (m *OfflineResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineResp.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineResp proto.InternalMessageInfo

type GetDeviceReq struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceReq) Reset()         { *m = GetDeviceReq{} }
func (m *GetDeviceReq) String() string { return proto.CompactTextString(m) }
func (*GetDeviceReq) ProtoMessage()    {}
func (*GetDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{8}
}

func (m *GetDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceReq.Unmarshal(m, b)
}
func (m *GetDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceReq.Marshal(b, m, deterministic)
}
func (m *GetDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceReq.Merge(m, src)
}
func (m *GetDeviceReq) XXX_Size() int {
	return xxx_messageInfo_GetDeviceReq.Size(m)
}
func (m *GetDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceReq proto.InternalMessageInfo

func (m *GetDeviceReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type GetDeviceResp struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceResp) Reset()         { *m = GetDeviceResp{} }
func (m *GetDeviceResp) String() string { return proto.CompactTextString(m) }
func (*GetDeviceResp) ProtoMessage()    {}
func (*GetDeviceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{9}
}

func (m *GetDeviceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceResp.Unmarshal(m, b)
}
func (m *GetDeviceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceResp.Marshal(b, m, deterministic)
}
func (m *GetDeviceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceResp.Merge(m, src)
}
func (m *GetDeviceResp) XXX_Size() int {
	return xxx_messageInfo_GetDeviceResp.Size(m)
}
func (m *GetDeviceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceResp proto.InternalMessageInfo

func (m *GetDeviceResp) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type Device struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Brand                string   `protobuf:"bytes,4,opt,name=Brand,proto3" json:"Brand,omitempty"`
	Model                string   `protobuf:"bytes,5,opt,name=Model,proto3" json:"Model,omitempty"`
	SystemVersion        string   `protobuf:"bytes,6,opt,name=SystemVersion,proto3" json:"SystemVersion,omitempty"`
	SDKVersion           string   `protobuf:"bytes,7,opt,name=SDKVersion,proto3" json:"SDKVersion,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	CreateTime           int64    `protobuf:"varint,9,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,10,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa14331f3fd0015e, []int{10}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Device) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Device) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Device) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *Device) GetSDKVersion() string {
	if m != nil {
		return m.SDKVersion
	}
	return ""
}

func (m *Device) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Device) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Device) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ConnSignInReq)(nil), "pb.ConnSignInReq")
	proto.RegisterType((*ConnSignInResp)(nil), "pb.ConnSignInResp")
	proto.RegisterType((*SyncReq)(nil), "pb.SyncReq")
	proto.RegisterType((*SyncResp)(nil), "pb.SyncResp")
	proto.RegisterType((*MessageACKReq)(nil), "pb.MessageACKReq")
	proto.RegisterType((*MessageACKResp)(nil), "pb.MessageACKResp")
	proto.RegisterType((*OfflineReq)(nil), "pb.OfflineReq")
	proto.RegisterType((*OfflineResp)(nil), "pb.OfflineResp")
	proto.RegisterType((*GetDeviceReq)(nil), "pb.GetDeviceReq")
	proto.RegisterType((*GetDeviceResp)(nil), "pb.GetDeviceResp")
	proto.RegisterType((*Device)(nil), "pb.Device")
}

func init() { proto.RegisterFile("logic.int.proto", fileDescriptor_aa14331f3fd0015e) }

var fileDescriptor_aa14331f3fd0015e = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdd, 0x6a, 0xdb, 0x40,
	0x10, 0x85, 0xb1, 0x95, 0xc8, 0xf2, 0x28, 0xce, 0xcf, 0xb6, 0xb4, 0x42, 0xa5, 0xc5, 0x11, 0xbd,
	0x30, 0x0d, 0x98, 0x62, 0x43, 0x7b, 0xed, 0x38, 0x50, 0x4c, 0x1a, 0x4a, 0xa5, 0xb4, 0xb7, 0x46,
	0xd6, 0x4e, 0x8c, 0xb0, 0xbd, 0xda, 0x68, 0x37, 0x21, 0x7e, 0x82, 0xbe, 0x44, 0x5f, 0xa1, 0xef,
	0x58, 0xf6, 0x27, 0xb6, 0xe4, 0x5e, 0x14, 0x7c, 0xa7, 0x39, 0xdf, 0xec, 0xec, 0x61, 0x7c, 0xd6,
	0x70, 0xb2, 0x2c, 0xe6, 0x79, 0xd6, 0xcf, 0x99, 0xec, 0xf3, 0xb2, 0x90, 0x05, 0x69, 0xf2, 0x59,
	0xd8, 0x96, 0x19, 0x37, 0x65, 0x68, 0x39, 0x3e, 0x59, 0x1e, 0x3d, 0x41, 0x67, 0x5c, 0x30, 0x96,
	0xe4, 0x73, 0x36, 0x61, 0x31, 0xde, 0x93, 0x37, 0xd0, 0xa6, 0xf8, 0x98, 0x67, 0x38, 0xcd, 0x69,
	0xd0, 0xe8, 0x36, 0x7a, 0x4e, 0xec, 0x19, 0x61, 0x42, 0xc9, 0x6b, 0x68, 0x3d, 0x08, 0x2c, 0x15,
	0x6a, 0x6a, 0xe4, 0xaa, 0x72, 0x42, 0xc9, 0x4b, 0x38, 0x94, 0xc5, 0x02, 0x59, 0xe0, 0x74, 0x1b,
	0xbd, 0x76, 0x6c, 0x0a, 0x35, 0x2b, 0x2b, 0x18, 0x9b, 0xa6, 0x94, 0x96, 0xc1, 0x81, 0x26, 0x9e,
	0x12, 0x46, 0x94, 0x96, 0xd1, 0x29, 0x1c, 0x57, 0x6f, 0x16, 0x3c, 0xfa, 0x0e, 0xad, 0x64, 0xcd,
	0x32, 0xe5, 0xa2, 0x72, 0x51, 0xa3, 0x76, 0x51, 0xcd, 0x5e, 0x73, 0xc7, 0xde, 0x29, 0x38, 0x02,
	0xef, 0xb5, 0x07, 0x27, 0x56, 0x9f, 0xd1, 0x67, 0xf0, 0xcc, 0x48, 0xc1, 0xc9, 0x05, 0x78, 0x2b,
	0x14, 0x22, 0x9d, 0xa3, 0x08, 0x9c, 0xae, 0xd3, 0xf3, 0x07, 0x27, 0x7d, 0x3e, 0xeb, 0xdf, 0x18,
	0x6d, 0x22, 0x71, 0x15, 0x6f, 0x1a, 0xa2, 0x5f, 0x0d, 0xe8, 0x58, 0x32, 0x1a, 0x5f, 0xef, 0x6f,
	0xe9, 0x2d, 0x80, 0x85, 0x69, 0xb6, 0xb0, 0xce, 0x6c, 0xfb, 0x28, 0x5b, 0x90, 0x73, 0x38, 0x2a,
	0x31, 0xc3, 0xfc, 0x11, 0xa7, 0x32, 0x5f, 0xa1, 0x5e, 0x92, 0x13, 0xfb, 0x56, 0xbb, 0xcd, 0x57,
	0xa8, 0xf6, 0x54, 0x35, 0x22, 0x78, 0x74, 0x09, 0xf0, 0xed, 0xee, 0x6e, 0x99, 0x33, 0xdc, 0xdb,
	0x57, 0xd4, 0x01, 0x7f, 0x33, 0x43, 0xf0, 0xe8, 0x02, 0x8e, 0xbe, 0xa0, 0xbc, 0xd2, 0xf4, 0x7f,
	0x29, 0x88, 0x86, 0xd0, 0xa9, 0x34, 0x0b, 0x4e, 0x22, 0x70, 0x0d, 0xd4, 0xad, 0xfe, 0x00, 0xd4,
	0x5e, 0x2d, 0xb7, 0x24, 0xfa, 0xdd, 0x04, 0xd7, 0x48, 0x7b, 0x46, 0x8c, 0xc0, 0xc1, 0xed, 0x9a,
	0xa3, 0xde, 0xe1, 0x61, 0xac, 0xbf, 0x55, 0xec, 0x2e, 0xcb, 0x94, 0x51, 0x1b, 0x2e, 0x53, 0x28,
	0xf5, 0xa6, 0xa0, 0xb8, 0x0c, 0x0e, 0x8d, 0xaa, 0x0b, 0xf2, 0x1e, 0x3a, 0xc9, 0x5a, 0x48, 0x5c,
	0xfd, 0xc4, 0x52, 0xe4, 0x05, 0x0b, 0x5c, 0x4d, 0xeb, 0x22, 0x79, 0x07, 0x90, 0x5c, 0x5d, 0x3f,
	0xb7, 0xb4, 0x74, 0x4b, 0x45, 0x21, 0xaf, 0xc0, 0x4d, 0x64, 0x2a, 0x1f, 0x44, 0xe0, 0x69, 0x1f,
	0xb6, 0x52, 0xe7, 0xc6, 0x25, 0xa6, 0x52, 0xff, 0x66, 0x41, 0x5b, 0x3b, 0xaf, 0x28, 0x8a, 0xff,
	0xe0, 0xf4, 0x99, 0x83, 0xe1, 0x5b, 0x65, 0xf0, 0xa7, 0x09, 0xde, 0x57, 0xf5, 0x36, 0x27, 0x4c,
	0x92, 0x21, 0xc0, 0xf6, 0x69, 0x90, 0x33, 0xb5, 0xcd, 0xda, 0x23, 0x0d, 0xc9, 0xae, 0x24, 0x38,
	0x39, 0x87, 0x03, 0x15, 0x75, 0xe2, 0x2b, 0x66, 0xdf, 0x51, 0x78, 0xb4, 0x2d, 0x04, 0x57, 0x73,
	0xb7, 0x51, 0x32, 0x73, 0x6b, 0x19, 0x37, 0x73, 0xeb, 0x69, 0x23, 0x1f, 0xa0, 0x65, 0x93, 0x42,
	0x8e, 0x15, 0xde, 0x46, 0x2f, 0x3c, 0xa9, 0xd5, 0x82, 0x93, 0x4f, 0xe0, 0x27, 0xc8, 0xa8, 0x9d,
	0x40, 0xf4, 0xb8, 0x8a, 0xa0, 0xce, 0xbc, 0xf8, 0x47, 0x13, 0x9c, 0x7c, 0x84, 0xf6, 0x26, 0x51,
	0xe4, 0x54, 0x75, 0x54, 0xd3, 0x18, 0x9e, 0xed, 0x28, 0x82, 0xcf, 0x5c, 0xfd, 0xf7, 0x35, 0xfc,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xd2, 0xf3, 0xfe, 0xf1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogicIntClient is the client API for LogicInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicIntClient interface {
	//  登录
	ConnSignIn(ctx context.Context, in *ConnSignInReq, opts ...grpc.CallOption) (*ConnSignInResp, error)
	//  消息同步
	Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error)
	//  设备收到消息回执
	MessageACK(ctx context.Context, in *MessageACKReq, opts ...grpc.CallOption) (*MessageACKResp, error)
	//  设备离线
	Offline(ctx context.Context, in *OfflineReq, opts ...grpc.CallOption) (*OfflineResp, error)
	// 发送消息
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 发送消息
	GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*GetDeviceResp, error)
}

type logicIntClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicIntClient(cc grpc.ClientConnInterface) LogicIntClient {
	return &logicIntClient{cc}
}

func (c *logicIntClient) ConnSignIn(ctx context.Context, in *ConnSignInReq, opts ...grpc.CallOption) (*ConnSignInResp, error) {
	out := new(ConnSignInResp)
	err := c.cc.Invoke(ctx, "/pb.LogicInt/ConnSignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicIntClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error) {
	out := new(SyncResp)
	err := c.cc.Invoke(ctx, "/pb.LogicInt/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicIntClient) MessageACK(ctx context.Context, in *MessageACKReq, opts ...grpc.CallOption) (*MessageACKResp, error) {
	out := new(MessageACKResp)
	err := c.cc.Invoke(ctx, "/pb.LogicInt/MessageACK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicIntClient) Offline(ctx context.Context, in *OfflineReq, opts ...grpc.CallOption) (*OfflineResp, error) {
	out := new(OfflineResp)
	err := c.cc.Invoke(ctx, "/pb.LogicInt/Offline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicIntClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, "/pb.LogicInt/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicIntClient) GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*GetDeviceResp, error) {
	out := new(GetDeviceResp)
	err := c.cc.Invoke(ctx, "/pb.LogicInt/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicIntServer is the server API for LogicInt service.
type LogicIntServer interface {
	//  登录
	ConnSignIn(context.Context, *ConnSignInReq) (*ConnSignInResp, error)
	//  消息同步
	Sync(context.Context, *SyncReq) (*SyncResp, error)
	//  设备收到消息回执
	MessageACK(context.Context, *MessageACKReq) (*MessageACKResp, error)
	//  设备离线
	Offline(context.Context, *OfflineReq) (*OfflineResp, error)
	// 发送消息
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// 发送消息
	GetDevice(context.Context, *GetDeviceReq) (*GetDeviceResp, error)
}

// UnimplementedLogicIntServer can be embedded to have forward compatible implementations.
type UnimplementedLogicIntServer struct {
}

func (*UnimplementedLogicIntServer) ConnSignIn(ctx context.Context, req *ConnSignInReq) (*ConnSignInResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnSignIn not implemented")
}
func (*UnimplementedLogicIntServer) Sync(ctx context.Context, req *SyncReq) (*SyncResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedLogicIntServer) MessageACK(ctx context.Context, req *MessageACKReq) (*MessageACKResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageACK not implemented")
}
func (*UnimplementedLogicIntServer) Offline(ctx context.Context, req *OfflineReq) (*OfflineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Offline not implemented")
}
func (*UnimplementedLogicIntServer) SendMessage(ctx context.Context, req *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedLogicIntServer) GetDevice(ctx context.Context, req *GetDeviceReq) (*GetDeviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}

func RegisterLogicIntServer(s *grpc.Server, srv LogicIntServer) {
	s.RegisterService(&_LogicInt_serviceDesc, srv)
}

func _LogicInt_ConnSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnSignInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicIntServer).ConnSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicInt/ConnSignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicIntServer).ConnSignIn(ctx, req.(*ConnSignInReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicInt_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicIntServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicInt/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicIntServer).Sync(ctx, req.(*SyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicInt_MessageACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageACKReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicIntServer).MessageACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicInt/MessageACK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicIntServer).MessageACK(ctx, req.(*MessageACKReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicInt_Offline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicIntServer).Offline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicInt/Offline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicIntServer).Offline(ctx, req.(*OfflineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicInt_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicIntServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicInt/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicIntServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicInt_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicIntServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicInt/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicIntServer).GetDevice(ctx, req.(*GetDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicInt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogicInt",
	HandlerType: (*LogicIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnSignIn",
			Handler:    _LogicInt_ConnSignIn_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _LogicInt_Sync_Handler,
		},
		{
			MethodName: "MessageACK",
			Handler:    _LogicInt_MessageACK_Handler,
		},
		{
			MethodName: "Offline",
			Handler:    _LogicInt_Offline_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _LogicInt_SendMessage_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _LogicInt_GetDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.int.proto",
}
