// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.ext.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterDeviceReq struct {
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemVersion        string   `protobuf:"bytes,5,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	SdkVersion           string   `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceReq) Reset()         { *m = RegisterDeviceReq{} }
func (m *RegisterDeviceReq) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceReq) ProtoMessage()    {}
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{0}
}

func (m *RegisterDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceReq.Unmarshal(m, b)
}
func (m *RegisterDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceReq.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceReq.Merge(m, src)
}
func (m *RegisterDeviceReq) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceReq.Size(m)
}
func (m *RegisterDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceReq proto.InternalMessageInfo

func (m *RegisterDeviceReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegisterDeviceReq) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *RegisterDeviceReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *RegisterDeviceReq) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *RegisterDeviceReq) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

type RegisterDeviceResp struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceResp) Reset()         { *m = RegisterDeviceResp{} }
func (m *RegisterDeviceResp) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceResp) ProtoMessage()    {}
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{1}
}

func (m *RegisterDeviceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceResp.Unmarshal(m, b)
}
func (m *RegisterDeviceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceResp.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceResp.Merge(m, src)
}
func (m *RegisterDeviceResp) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceResp.Size(m)
}
func (m *RegisterDeviceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceResp proto.InternalMessageInfo

func (m *RegisterDeviceResp) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type SendMessageReq struct {
	ReceiverType         ReceiverType `protobuf:"varint,1,opt,name=receiver_type,json=receiverType,proto3,enum=pb.ReceiverType" json:"receiver_type,omitempty"`
	ReceiverId           int64        `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ToUserIds            []int64      `protobuf:"varint,3,rep,packed,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`
	MessageType          MessageType  `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=pb.MessageType" json:"message_type,omitempty"`
	MessageContent       []byte       `protobuf:"bytes,5,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	SendTime             int64        `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	IsPersist            bool         `protobuf:"varint,7,opt,name=is_persist,json=isPersist,proto3" json:"is_persist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{2}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetReceiverType() ReceiverType {
	if m != nil {
		return m.ReceiverType
	}
	return ReceiverType_RT_UNKNOWN
}

func (m *SendMessageReq) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *SendMessageReq) GetToUserIds() []int64 {
	if m != nil {
		return m.ToUserIds
	}
	return nil
}

func (m *SendMessageReq) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_MT_UNKNOWN
}

func (m *SendMessageReq) GetMessageContent() []byte {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

func (m *SendMessageReq) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *SendMessageReq) GetIsPersist() bool {
	if m != nil {
		return m.IsPersist
	}
	return false
}

type SendMessageResp struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{3}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func (m *SendMessageResp) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type AddFriendReq struct {
	FriendId             int64    `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remarks              string   `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendReq) Reset()         { *m = AddFriendReq{} }
func (m *AddFriendReq) String() string { return proto.CompactTextString(m) }
func (*AddFriendReq) ProtoMessage()    {}
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{4}
}

func (m *AddFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendReq.Unmarshal(m, b)
}
func (m *AddFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendReq.Marshal(b, m, deterministic)
}
func (m *AddFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendReq.Merge(m, src)
}
func (m *AddFriendReq) XXX_Size() int {
	return xxx_messageInfo_AddFriendReq.Size(m)
}
func (m *AddFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendReq proto.InternalMessageInfo

func (m *AddFriendReq) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *AddFriendReq) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *AddFriendReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AddFriendResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendResp) Reset()         { *m = AddFriendResp{} }
func (m *AddFriendResp) String() string { return proto.CompactTextString(m) }
func (*AddFriendResp) ProtoMessage()    {}
func (*AddFriendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{5}
}

func (m *AddFriendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendResp.Unmarshal(m, b)
}
func (m *AddFriendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendResp.Marshal(b, m, deterministic)
}
func (m *AddFriendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendResp.Merge(m, src)
}
func (m *AddFriendResp) XXX_Size() int {
	return xxx_messageInfo_AddFriendResp.Size(m)
}
func (m *AddFriendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendResp proto.InternalMessageInfo

type AgreeAddFriendReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Remarks              string   `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeAddFriendReq) Reset()         { *m = AgreeAddFriendReq{} }
func (m *AgreeAddFriendReq) String() string { return proto.CompactTextString(m) }
func (*AgreeAddFriendReq) ProtoMessage()    {}
func (*AgreeAddFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{6}
}

func (m *AgreeAddFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeAddFriendReq.Unmarshal(m, b)
}
func (m *AgreeAddFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeAddFriendReq.Marshal(b, m, deterministic)
}
func (m *AgreeAddFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeAddFriendReq.Merge(m, src)
}
func (m *AgreeAddFriendReq) XXX_Size() int {
	return xxx_messageInfo_AgreeAddFriendReq.Size(m)
}
func (m *AgreeAddFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeAddFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeAddFriendReq proto.InternalMessageInfo

func (m *AgreeAddFriendReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AgreeAddFriendReq) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

type AgreeAddFriendResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeAddFriendResp) Reset()         { *m = AgreeAddFriendResp{} }
func (m *AgreeAddFriendResp) String() string { return proto.CompactTextString(m) }
func (*AgreeAddFriendResp) ProtoMessage()    {}
func (*AgreeAddFriendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{7}
}

func (m *AgreeAddFriendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeAddFriendResp.Unmarshal(m, b)
}
func (m *AgreeAddFriendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeAddFriendResp.Marshal(b, m, deterministic)
}
func (m *AgreeAddFriendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeAddFriendResp.Merge(m, src)
}
func (m *AgreeAddFriendResp) XXX_Size() int {
	return xxx_messageInfo_AgreeAddFriendResp.Size(m)
}
func (m *AgreeAddFriendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeAddFriendResp.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeAddFriendResp proto.InternalMessageInfo

type Friend struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	UserExtra            string   `protobuf:"bytes,6,opt,name=user_extra,json=userExtra,proto3" json:"user_extra,omitempty"`
	Remarks              string   `protobuf:"bytes,7,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Extra                string   `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{8}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Friend) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Friend) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Friend) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Friend) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Friend) GetUserExtra() string {
	if m != nil {
		return m.UserExtra
	}
	return ""
}

func (m *Friend) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *Friend) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type GetFriendsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendsReq) Reset()         { *m = GetFriendsReq{} }
func (m *GetFriendsReq) String() string { return proto.CompactTextString(m) }
func (*GetFriendsReq) ProtoMessage()    {}
func (*GetFriendsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{9}
}

func (m *GetFriendsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsReq.Unmarshal(m, b)
}
func (m *GetFriendsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsReq.Marshal(b, m, deterministic)
}
func (m *GetFriendsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsReq.Merge(m, src)
}
func (m *GetFriendsReq) XXX_Size() int {
	return xxx_messageInfo_GetFriendsReq.Size(m)
}
func (m *GetFriendsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsReq proto.InternalMessageInfo

type GetFriendsResp struct {
	Friends              []*Friend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFriendsResp) Reset()         { *m = GetFriendsResp{} }
func (m *GetFriendsResp) String() string { return proto.CompactTextString(m) }
func (*GetFriendsResp) ProtoMessage()    {}
func (*GetFriendsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{10}
}

func (m *GetFriendsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsResp.Unmarshal(m, b)
}
func (m *GetFriendsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsResp.Marshal(b, m, deterministic)
}
func (m *GetFriendsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsResp.Merge(m, src)
}
func (m *GetFriendsResp) XXX_Size() int {
	return xxx_messageInfo_GetFriendsResp.Size(m)
}
func (m *GetFriendsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsResp proto.InternalMessageInfo

func (m *GetFriendsResp) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

type CreateGroupReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReq) Reset()         { *m = CreateGroupReq{} }
func (m *CreateGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReq) ProtoMessage()    {}
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{11}
}

func (m *CreateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReq.Unmarshal(m, b)
}
func (m *CreateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReq.Merge(m, src)
}
func (m *CreateGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReq.Size(m)
}
func (m *CreateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReq proto.InternalMessageInfo

func (m *CreateGroupReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupReq) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateGroupReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateGroupReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type CreateGroupResp struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResp) Reset()         { *m = CreateGroupResp{} }
func (m *CreateGroupResp) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResp) ProtoMessage()    {}
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{12}
}

func (m *CreateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResp.Unmarshal(m, b)
}
func (m *CreateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResp.Marshal(b, m, deterministic)
}
func (m *CreateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResp.Merge(m, src)
}
func (m *CreateGroupResp) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResp.Size(m)
}
func (m *CreateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResp proto.InternalMessageInfo

func (m *CreateGroupResp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type UpdateGroupReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupReq) Reset()         { *m = UpdateGroupReq{} }
func (m *UpdateGroupReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupReq) ProtoMessage()    {}
func (*UpdateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{13}
}

func (m *UpdateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupReq.Unmarshal(m, b)
}
func (m *UpdateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupReq.Merge(m, src)
}
func (m *UpdateGroupReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupReq.Size(m)
}
func (m *UpdateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupReq proto.InternalMessageInfo

func (m *UpdateGroupReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *UpdateGroupReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateGroupReq) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateGroupReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type UpdateGroupResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResp) Reset()         { *m = UpdateGroupResp{} }
func (m *UpdateGroupResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResp) ProtoMessage()    {}
func (*UpdateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{14}
}

func (m *UpdateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResp.Unmarshal(m, b)
}
func (m *UpdateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResp.Merge(m, src)
}
func (m *UpdateGroupResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResp.Size(m)
}
func (m *UpdateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResp proto.InternalMessageInfo

type GetGroupReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupReq) Reset()         { *m = GetGroupReq{} }
func (m *GetGroupReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupReq) ProtoMessage()    {}
func (*GetGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{15}
}

func (m *GetGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupReq.Unmarshal(m, b)
}
func (m *GetGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupReq.Marshal(b, m, deterministic)
}
func (m *GetGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupReq.Merge(m, src)
}
func (m *GetGroupReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupReq.Size(m)
}
func (m *GetGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupReq proto.InternalMessageInfo

func (m *GetGroupReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GetGroupResp struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResp) Reset()         { *m = GetGroupResp{} }
func (m *GetGroupResp) String() string { return proto.CompactTextString(m) }
func (*GetGroupResp) ProtoMessage()    {}
func (*GetGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{16}
}

func (m *GetGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResp.Unmarshal(m, b)
}
func (m *GetGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResp.Marshal(b, m, deterministic)
}
func (m *GetGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResp.Merge(m, src)
}
func (m *GetGroupResp) XXX_Size() int {
	return xxx_messageInfo_GetGroupResp.Size(m)
}
func (m *GetGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResp proto.InternalMessageInfo

func (m *GetGroupResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type Group struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	UserMum              int32    `protobuf:"varint,4,opt,name=user_mum,json=userMum,proto3" json:"user_mum,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Extra                string   `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	CreateTime           int64    `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{17}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Group) GetUserMum() int32 {
	if m != nil {
		return m.UserMum
	}
	return 0
}

func (m *Group) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Group) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *Group) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Group) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type GetUserGroupsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserGroupsReq) Reset()         { *m = GetUserGroupsReq{} }
func (m *GetUserGroupsReq) String() string { return proto.CompactTextString(m) }
func (*GetUserGroupsReq) ProtoMessage()    {}
func (*GetUserGroupsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{18}
}

func (m *GetUserGroupsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGroupsReq.Unmarshal(m, b)
}
func (m *GetUserGroupsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGroupsReq.Marshal(b, m, deterministic)
}
func (m *GetUserGroupsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGroupsReq.Merge(m, src)
}
func (m *GetUserGroupsReq) XXX_Size() int {
	return xxx_messageInfo_GetUserGroupsReq.Size(m)
}
func (m *GetUserGroupsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGroupsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGroupsReq proto.InternalMessageInfo

type GetUserGroupsResp struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserGroupsResp) Reset()         { *m = GetUserGroupsResp{} }
func (m *GetUserGroupsResp) String() string { return proto.CompactTextString(m) }
func (*GetUserGroupsResp) ProtoMessage()    {}
func (*GetUserGroupsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{19}
}

func (m *GetUserGroupsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGroupsResp.Unmarshal(m, b)
}
func (m *GetUserGroupsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGroupsResp.Marshal(b, m, deterministic)
}
func (m *GetUserGroupsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGroupsResp.Merge(m, src)
}
func (m *GetUserGroupsResp) XXX_Size() int {
	return xxx_messageInfo_GetUserGroupsResp.Size(m)
}
func (m *GetUserGroupsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGroupsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGroupsResp proto.InternalMessageInfo

func (m *GetUserGroupsResp) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

// 群组用户
type GroupUser struct {
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupUser) Reset()         { *m = GroupUser{} }
func (m *GroupUser) String() string { return proto.CompactTextString(m) }
func (*GroupUser) ProtoMessage()    {}
func (*GroupUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{20}
}

func (m *GroupUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupUser.Unmarshal(m, b)
}
func (m *GroupUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupUser.Marshal(b, m, deterministic)
}
func (m *GroupUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupUser.Merge(m, src)
}
func (m *GroupUser) XXX_Size() int {
	return xxx_messageInfo_GroupUser.Size(m)
}
func (m *GroupUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupUser.DiscardUnknown(m)
}

var xxx_messageInfo_GroupUser proto.InternalMessageInfo

func (m *GroupUser) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *GroupUser) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type AddGroupMemberReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Remarks              string   `protobuf:"bytes,3,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberReq) Reset()         { *m = AddGroupMemberReq{} }
func (m *AddGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberReq) ProtoMessage()    {}
func (*AddGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{21}
}

func (m *AddGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberReq.Unmarshal(m, b)
}
func (m *AddGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberReq.Merge(m, src)
}
func (m *AddGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberReq.Size(m)
}
func (m *AddGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberReq proto.InternalMessageInfo

func (m *AddGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *AddGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddGroupMemberReq) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *AddGroupMemberReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type AddGroupMemberResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberResp) Reset()         { *m = AddGroupMemberResp{} }
func (m *AddGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberResp) ProtoMessage()    {}
func (*AddGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{22}
}

func (m *AddGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberResp.Unmarshal(m, b)
}
func (m *AddGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberResp.Merge(m, src)
}
func (m *AddGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberResp.Size(m)
}
func (m *AddGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberResp proto.InternalMessageInfo

type UpdateGroupMemberReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Remarks              string   `protobuf:"bytes,3,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupMemberReq) Reset()         { *m = UpdateGroupMemberReq{} }
func (m *UpdateGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMemberReq) ProtoMessage()    {}
func (*UpdateGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{23}
}

func (m *UpdateGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMemberReq.Unmarshal(m, b)
}
func (m *UpdateGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMemberReq.Merge(m, src)
}
func (m *UpdateGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMemberReq.Size(m)
}
func (m *UpdateGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMemberReq proto.InternalMessageInfo

func (m *UpdateGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *UpdateGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateGroupMemberReq) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *UpdateGroupMemberReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type UpdateGroupMemberResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupMemberResp) Reset()         { *m = UpdateGroupMemberResp{} }
func (m *UpdateGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMemberResp) ProtoMessage()    {}
func (*UpdateGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{24}
}

func (m *UpdateGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMemberResp.Unmarshal(m, b)
}
func (m *UpdateGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMemberResp.Merge(m, src)
}
func (m *UpdateGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMemberResp.Size(m)
}
func (m *UpdateGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMemberResp proto.InternalMessageInfo

type DeleteGroupMemberReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupMemberReq) Reset()         { *m = DeleteGroupMemberReq{} }
func (m *DeleteGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupMemberReq) ProtoMessage()    {}
func (*DeleteGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{25}
}

func (m *DeleteGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupMemberReq.Unmarshal(m, b)
}
func (m *DeleteGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *DeleteGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupMemberReq.Merge(m, src)
}
func (m *DeleteGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupMemberReq.Size(m)
}
func (m *DeleteGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupMemberReq proto.InternalMessageInfo

func (m *DeleteGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *DeleteGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteGroupMemberResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupMemberResp) Reset()         { *m = DeleteGroupMemberResp{} }
func (m *DeleteGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupMemberResp) ProtoMessage()    {}
func (*DeleteGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{26}
}

func (m *DeleteGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupMemberResp.Unmarshal(m, b)
}
func (m *DeleteGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *DeleteGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupMemberResp.Merge(m, src)
}
func (m *DeleteGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupMemberResp.Size(m)
}
func (m *DeleteGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupMemberResp proto.InternalMessageInfo

type GetGroupMembersReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupMembersReq) Reset()         { *m = GetGroupMembersReq{} }
func (m *GetGroupMembersReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupMembersReq) ProtoMessage()    {}
func (*GetGroupMembersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{27}
}

func (m *GetGroupMembersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupMembersReq.Unmarshal(m, b)
}
func (m *GetGroupMembersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupMembersReq.Marshal(b, m, deterministic)
}
func (m *GetGroupMembersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupMembersReq.Merge(m, src)
}
func (m *GetGroupMembersReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupMembersReq.Size(m)
}
func (m *GetGroupMembersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupMembersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupMembersReq proto.InternalMessageInfo

func (m *GetGroupMembersReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GetGroupMembersResp struct {
	Members              []*GroupMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetGroupMembersResp) Reset()         { *m = GetGroupMembersResp{} }
func (m *GetGroupMembersResp) String() string { return proto.CompactTextString(m) }
func (*GetGroupMembersResp) ProtoMessage()    {}
func (*GetGroupMembersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{28}
}

func (m *GetGroupMembersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupMembersResp.Unmarshal(m, b)
}
func (m *GetGroupMembersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupMembersResp.Marshal(b, m, deterministic)
}
func (m *GetGroupMembersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupMembersResp.Merge(m, src)
}
func (m *GetGroupMembersResp) XXX_Size() int {
	return xxx_messageInfo_GetGroupMembersResp.Size(m)
}
func (m *GetGroupMembersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupMembersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupMembersResp proto.InternalMessageInfo

func (m *GetGroupMembersResp) GetMembers() []*GroupMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupMember struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	UserExtra            string   `protobuf:"bytes,5,opt,name=user_extra,json=userExtra,proto3" json:"user_extra,omitempty"`
	Remarks              string   `protobuf:"bytes,6,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Extra                string   `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMember) Reset()         { *m = GroupMember{} }
func (m *GroupMember) String() string { return proto.CompactTextString(m) }
func (*GroupMember) ProtoMessage()    {}
func (*GroupMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{29}
}

func (m *GroupMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMember.Unmarshal(m, b)
}
func (m *GroupMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMember.Marshal(b, m, deterministic)
}
func (m *GroupMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMember.Merge(m, src)
}
func (m *GroupMember) XXX_Size() int {
	return xxx_messageInfo_GroupMember.Size(m)
}
func (m *GroupMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMember.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMember proto.InternalMessageInfo

func (m *GroupMember) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupMember) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GroupMember) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *GroupMember) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *GroupMember) GetUserExtra() string {
	if m != nil {
		return m.UserExtra
	}
	return ""
}

func (m *GroupMember) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *GroupMember) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterDeviceReq)(nil), "pb.RegisterDeviceReq")
	proto.RegisterType((*RegisterDeviceResp)(nil), "pb.RegisterDeviceResp")
	proto.RegisterType((*SendMessageReq)(nil), "pb.SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "pb.SendMessageResp")
	proto.RegisterType((*AddFriendReq)(nil), "pb.AddFriendReq")
	proto.RegisterType((*AddFriendResp)(nil), "pb.AddFriendResp")
	proto.RegisterType((*AgreeAddFriendReq)(nil), "pb.AgreeAddFriendReq")
	proto.RegisterType((*AgreeAddFriendResp)(nil), "pb.AgreeAddFriendResp")
	proto.RegisterType((*Friend)(nil), "pb.Friend")
	proto.RegisterType((*GetFriendsReq)(nil), "pb.GetFriendsReq")
	proto.RegisterType((*GetFriendsResp)(nil), "pb.GetFriendsResp")
	proto.RegisterType((*CreateGroupReq)(nil), "pb.CreateGroupReq")
	proto.RegisterType((*CreateGroupResp)(nil), "pb.CreateGroupResp")
	proto.RegisterType((*UpdateGroupReq)(nil), "pb.UpdateGroupReq")
	proto.RegisterType((*UpdateGroupResp)(nil), "pb.UpdateGroupResp")
	proto.RegisterType((*GetGroupReq)(nil), "pb.GetGroupReq")
	proto.RegisterType((*GetGroupResp)(nil), "pb.GetGroupResp")
	proto.RegisterType((*Group)(nil), "pb.Group")
	proto.RegisterType((*GetUserGroupsReq)(nil), "pb.GetUserGroupsReq")
	proto.RegisterType((*GetUserGroupsResp)(nil), "pb.GetUserGroupsResp")
	proto.RegisterType((*GroupUser)(nil), "pb.GroupUser")
	proto.RegisterType((*AddGroupMemberReq)(nil), "pb.AddGroupMemberReq")
	proto.RegisterType((*AddGroupMemberResp)(nil), "pb.AddGroupMemberResp")
	proto.RegisterType((*UpdateGroupMemberReq)(nil), "pb.UpdateGroupMemberReq")
	proto.RegisterType((*UpdateGroupMemberResp)(nil), "pb.UpdateGroupMemberResp")
	proto.RegisterType((*DeleteGroupMemberReq)(nil), "pb.DeleteGroupMemberReq")
	proto.RegisterType((*DeleteGroupMemberResp)(nil), "pb.DeleteGroupMemberResp")
	proto.RegisterType((*GetGroupMembersReq)(nil), "pb.GetGroupMembersReq")
	proto.RegisterType((*GetGroupMembersResp)(nil), "pb.GetGroupMembersResp")
	proto.RegisterType((*GroupMember)(nil), "pb.GroupMember")
}

func init() { proto.RegisterFile("logic.ext.proto", fileDescriptor_f5bf3fa139aedf16) }

var fileDescriptor_f5bf3fa139aedf16 = []byte{
	// 1156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x72, 0xe3, 0x44,
	0x13, 0x2d, 0x59, 0xf1, 0x8f, 0x5a, 0x5e, 0x3b, 0xee, 0x75, 0x36, 0x8e, 0xb7, 0xbe, 0x2f, 0xde,
	0x01, 0x0a, 0x53, 0x05, 0x59, 0xc8, 0x16, 0xe1, 0x86, 0x2a, 0x08, 0xfb, 0x13, 0x42, 0x11, 0x8a,
	0x12, 0x1b, 0x6e, 0x5d, 0xb6, 0x35, 0x18, 0x55, 0x2c, 0x69, 0xa2, 0x91, 0x43, 0xc2, 0xab, 0x70,
	0xb5, 0xaf, 0xc2, 0x93, 0xc0, 0x9b, 0x50, 0xd3, 0x33, 0xb6, 0x25, 0x59, 0xce, 0x72, 0x01, 0xdc,
	0xb9, 0x4f, 0xcf, 0xa8, 0xbb, 0x4f, 0xcf, 0x9c, 0x1e, 0x43, 0x7b, 0x1e, 0xcf, 0x82, 0xe9, 0x11,
	0xbf, 0x4d, 0x8f, 0x44, 0x12, 0xa7, 0x31, 0x56, 0xc4, 0xa4, 0xdf, 0x9a, 0xc6, 0x51, 0xb4, 0xc6,
	0xd8, 0x6f, 0x16, 0x74, 0x3c, 0x3e, 0x0b, 0x64, 0xca, 0x93, 0x17, 0xfc, 0x26, 0x98, 0x72, 0x8f,
	0x5f, 0x23, 0xc2, 0x4e, 0x7a, 0x27, 0x78, 0xaf, 0x32, 0xb0, 0x86, 0x55, 0x8f, 0x7e, 0x63, 0x17,
	0xaa, 0x93, 0x64, 0x1c, 0xf9, 0x3d, 0x7b, 0x60, 0x0d, 0x1d, 0x4f, 0x1b, 0x0a, 0x0d, 0x63, 0x9f,
	0xcf, 0x7b, 0x3b, 0x1a, 0x25, 0x03, 0xdf, 0x83, 0x96, 0xbc, 0x93, 0x29, 0x0f, 0x47, 0x37, 0x3c,
	0x91, 0x41, 0x1c, 0xf5, 0xaa, 0xe4, 0x7e, 0xa0, 0xd1, 0x1f, 0x35, 0x88, 0x87, 0xe0, 0x4a, 0xff,
	0x6a, 0xb5, 0xa6, 0x46, 0x6b, 0x40, 0xfa, 0x57, 0x66, 0x01, 0xfb, 0x04, 0xb0, 0x98, 0x9c, 0x14,
	0xf8, 0x18, 0x1c, 0x9f, 0xac, 0x51, 0xe0, 0xf7, 0xac, 0x81, 0x35, 0xb4, 0xbd, 0x86, 0x06, 0xce,
	0x7d, 0xf6, 0xa6, 0x02, 0xad, 0x1f, 0x78, 0xe4, 0x5f, 0x70, 0x29, 0xc7, 0x33, 0xaa, 0xe6, 0x53,
	0x78, 0x90, 0xf0, 0x29, 0x0f, 0x6e, 0x78, 0x32, 0xa2, 0xb2, 0xd4, 0x9e, 0xd6, 0xf1, 0xee, 0x91,
	0x98, 0x1c, 0x79, 0xc6, 0xf1, 0xfa, 0x4e, 0x70, 0xaf, 0x99, 0x64, 0x2c, 0x95, 0xdd, 0x6a, 0x5b,
	0xe0, 0x13, 0x17, 0xb6, 0x07, 0x4b, 0xe8, 0xdc, 0xc7, 0xff, 0x83, 0x9b, 0xc6, 0xa3, 0x85, 0x24,
	0xbf, 0xec, 0xd9, 0x03, 0x7b, 0x68, 0x7b, 0x4e, 0x1a, 0x5f, 0x4a, 0xe5, 0x96, 0x78, 0x0c, 0xcd,
	0x50, 0x67, 0xa1, 0xc3, 0xee, 0x50, 0xd8, 0xb6, 0x0a, 0x6b, 0xb2, 0xa3, 0xa8, 0x6e, 0xb8, 0x36,
	0xf0, 0x7d, 0x68, 0x2f, 0xf7, 0x4c, 0xe3, 0x28, 0xe5, 0x51, 0x4a, 0xd4, 0x35, 0xbd, 0x96, 0x81,
	0x9f, 0x6b, 0x54, 0x91, 0x20, 0x79, 0xe4, 0x8f, 0xd2, 0x20, 0xe4, 0xc4, 0x9c, 0xed, 0x35, 0x14,
	0xf0, 0x3a, 0x08, 0x39, 0xfe, 0x0f, 0x20, 0x90, 0x23, 0xa1, 0x58, 0x94, 0x69, 0xaf, 0x3e, 0xb0,
	0x86, 0x0d, 0xcf, 0x09, 0xe4, 0xf7, 0x1a, 0x60, 0xef, 0x40, 0x3b, 0x47, 0x91, 0x14, 0xb8, 0x0b,
	0xb6, 0xe4, 0xd7, 0x86, 0x4d, 0xf5, 0x93, 0xcd, 0xa0, 0x79, 0xea, 0xfb, 0xaf, 0x92, 0x80, 0x47,
	0xbe, 0x62, 0xf1, 0x31, 0x38, 0x3f, 0x91, 0x91, 0x61, 0x5d, 0x03, 0xe7, 0x3e, 0xf6, 0xa0, 0x9e,
	0xf0, 0x70, 0x9c, 0x5c, 0x49, 0xe2, 0xc9, 0xf1, 0x96, 0x26, 0x0e, 0xc0, 0xf5, 0xb9, 0x9c, 0x26,
	0x81, 0x48, 0x55, 0x8f, 0xf5, 0xe1, 0xc9, 0x42, 0xac, 0x0d, 0x0f, 0x32, 0x81, 0xa4, 0x60, 0xaf,
	0xa0, 0x73, 0x3a, 0x4b, 0x38, 0xcf, 0x85, 0xdf, 0x87, 0xba, 0x61, 0xda, 0x04, 0xaf, 0x2d, 0x88,
	0xe6, 0xed, 0xa1, 0x59, 0x17, 0xb0, 0xf8, 0x1d, 0x29, 0xd8, 0x1f, 0x16, 0xd4, 0xb4, 0xb9, 0xfd,
	0x9b, 0x4f, 0xa0, 0x29, 0x7e, 0x8e, 0x23, 0x3e, 0x8a, 0x16, 0xe1, 0x84, 0x27, 0xe6, 0xc3, 0x2e,
	0x61, 0xdf, 0x11, 0x84, 0x7d, 0x68, 0x44, 0xc1, 0xf4, 0x2a, 0x1a, 0x87, 0xdc, 0x14, 0xb5, 0xb2,
	0x35, 0x99, 0xb7, 0xd4, 0xef, 0xaa, 0x22, 0xf3, 0x56, 0x35, 0x64, 0x7c, 0x33, 0x4e, 0xc7, 0xc9,
	0x68, 0x91, 0xcc, 0xcd, 0x65, 0x70, 0x34, 0x72, 0x99, 0xcc, 0x95, 0x9b, 0x12, 0xe1, 0xb7, 0x69,
	0x32, 0x36, 0xf7, 0xc0, 0x51, 0xc8, 0x4b, 0x05, 0x64, 0x4b, 0xac, 0xe7, 0xd9, 0xed, 0x42, 0x55,
	0xef, 0x69, 0xe8, 0xeb, 0x47, 0x86, 0x62, 0xf4, 0x8c, 0xa7, 0xba, 0x48, 0xe9, 0xf1, 0x6b, 0x76,
	0x02, 0xad, 0x2c, 0x20, 0x05, 0xbe, 0x0b, 0x75, 0xdd, 0x3c, 0xd9, 0xb3, 0x06, 0xf6, 0xd0, 0x3d,
	0x06, 0x75, 0x2c, 0x0d, 0x4d, 0x4b, 0x17, 0x4b, 0xa0, 0xf5, 0x3c, 0xe1, 0xe3, 0x94, 0x9f, 0x25,
	0xf1, 0x42, 0x18, 0x65, 0xa0, 0x92, 0x2d, 0x8a, 0x47, 0xbf, 0x91, 0x41, 0x33, 0x88, 0xd2, 0x24,
	0xf6, 0x17, 0x53, 0xea, 0xb1, 0x66, 0x2b, 0x87, 0xad, 0x14, 0xc5, 0xce, 0x2b, 0x8a, 0x4e, 0x7e,
	0x27, 0x9b, 0xfc, 0x87, 0xd0, 0xce, 0xc5, 0x94, 0x02, 0x0f, 0xa0, 0x31, 0x53, 0xc6, 0xba, 0x51,
	0x75, 0xb2, 0xcf, 0x7d, 0x76, 0x07, 0xad, 0x4b, 0xe1, 0x67, 0x33, 0xdc, 0xbe, 0x78, 0x95, 0x7c,
	0xe5, 0x9e, 0xe4, 0xed, 0x92, 0xe4, 0xcb, 0x13, 0xed, 0x40, 0x3b, 0x17, 0x5a, 0x0a, 0x36, 0x04,
	0xf7, 0x8c, 0xa7, 0x7f, 0x23, 0x15, 0xf6, 0x14, 0x9a, 0xeb, 0x95, 0x52, 0xe0, 0x21, 0x54, 0xc9,
	0x45, 0xeb, 0xdc, 0x63, 0x47, 0x75, 0x43, 0x7b, 0x35, 0xce, 0xfe, 0xb4, 0xa0, 0x4a, 0xc0, 0xbf,
	0x51, 0xe0, 0x01, 0x34, 0xe8, 0xfc, 0x85, 0x8b, 0xd0, 0x9c, 0x5a, 0xba, 0x18, 0x17, 0x8b, 0x70,
	0xd5, 0xb8, 0x6a, 0x59, 0xe3, 0x6a, 0x19, 0x3e, 0x94, 0x5e, 0x4e, 0xa9, 0x71, 0x5a, 0x93, 0xea,
	0x5a, 0x2f, 0x35, 0x44, 0xaa, 0x74, 0x08, 0xee, 0x82, 0x08, 0xd3, 0x0b, 0x1a, 0x7a, 0x81, 0x86,
	0xd4, 0x02, 0x86, 0xb0, 0x7b, 0xc6, 0x53, 0x25, 0x9f, 0x54, 0xa9, 0x39, 0xba, 0x9d, 0x02, 0x26,
	0x05, 0x3e, 0x81, 0x1a, 0x95, 0xbc, 0x3c, 0xbc, 0x19, 0xba, 0x8c, 0x83, 0x7d, 0x06, 0x0e, 0x01,
	0x6a, 0xa7, 0x4a, 0x78, 0x3e, 0x9e, 0xf0, 0xf9, 0x72, 0x76, 0x91, 0xb1, 0xa5, 0xad, 0xbf, 0x40,
	0xe7, 0xd4, 0xf7, 0x69, 0xef, 0x05, 0x57, 0x57, 0xfd, 0x2d, 0x87, 0x2a, 0x23, 0x22, 0x95, 0x6d,
	0xc2, 0x64, 0x6f, 0xb9, 0xb5, 0xb9, 0xc0, 0x4a, 0xae, 0x0a, 0x81, 0xa5, 0x60, 0xbf, 0x42, 0x37,
	0x73, 0xca, 0xfe, 0xdb, 0x8c, 0xf6, 0x61, 0xaf, 0x24, 0xb6, 0x14, 0xec, 0x1b, 0xe8, 0xbe, 0xe0,
	0x73, 0xfe, 0x4f, 0x24, 0xa5, 0x82, 0x94, 0x7c, 0x4b, 0x0a, 0xf6, 0x14, 0x70, 0x79, 0x45, 0x34,
	0x2a, 0xdf, 0x72, 0xa7, 0xbe, 0x84, 0x87, 0x1b, 0x1b, 0xa4, 0xc0, 0x0f, 0xa0, 0x1e, 0x6a, 0xd3,
	0x9c, 0x96, 0xf6, 0xea, 0xb4, 0x98, 0x68, 0x4b, 0x3f, 0xfb, 0xdd, 0x02, 0x37, 0xe3, 0xd8, 0x3e,
	0x20, 0xb2, 0xea, 0x5f, 0x29, 0x57, 0x7f, 0x7b, 0x9b, 0xfa, 0xef, 0xdc, 0xaf, 0xfe, 0xd5, 0x7b,
	0xd4, 0xbf, 0xb6, 0xa5, 0x6b, 0xf5, 0x4c, 0xd7, 0x8e, 0xdf, 0xd4, 0xa0, 0xf1, 0xad, 0x7a, 0xfa,
	0xbd, 0xbc, 0x4d, 0xf1, 0x0b, 0x68, 0xe5, 0x5f, 0x50, 0xb8, 0xa7, 0x9f, 0x3d, 0x85, 0x27, 0x5f,
	0xff, 0x51, 0x19, 0x2c, 0x05, 0x9e, 0x80, 0x9b, 0x79, 0x2b, 0x20, 0xaa, 0x65, 0xf9, 0xf7, 0x55,
	0xff, 0xe1, 0x06, 0x26, 0x05, 0x7e, 0x0c, 0xce, 0x6a, 0xee, 0x22, 0x3d, 0xb5, 0xb2, 0xe3, 0xbc,
	0xdf, 0x29, 0x20, 0x52, 0xa8, 0x54, 0xf3, 0xe3, 0x5a, 0xa7, 0xba, 0xf1, 0x14, 0xd0, 0xa9, 0x6e,
	0x4e, 0x76, 0x7c, 0x06, 0xb0, 0x9e, 0x72, 0x48, 0x11, 0x72, 0x63, 0xb0, 0x8f, 0x45, 0x48, 0xd7,
	0x97, 0x19, 0x37, 0xba, 0xbe, 0xfc, 0xcc, 0xd3, 0xf5, 0x15, 0x67, 0xd2, 0x09, 0xb8, 0x99, 0xbb,
	0xa1, 0xf7, 0xe5, 0x27, 0x91, 0xde, 0x57, 0x18, 0x11, 0xf8, 0x11, 0x34, 0x96, 0x87, 0x14, 0xdb,
	0x26, 0x9f, 0xd5, 0x8e, 0xdd, 0x3c, 0x20, 0x05, 0x7e, 0x4e, 0xa3, 0x7c, 0x2d, 0x7f, 0xd8, 0x35,
	0x4b, 0x72, 0x2a, 0xd9, 0xdf, 0x2b, 0x41, 0x0d, 0xa5, 0x39, 0x49, 0x31, 0x94, 0x16, 0xf5, 0xcd,
	0x50, 0xba, 0xa1, 0x3e, 0xf8, 0x35, 0x74, 0x36, 0x14, 0x00, 0x7b, 0x85, 0xba, 0xd6, 0x9f, 0x39,
	0xd8, 0xe2, 0xd1, 0x5f, 0xda, 0xb8, 0xe6, 0xfa, 0x4b, 0x65, 0x4a, 0xa2, 0xbf, 0x54, 0xaa, 0x0b,
	0xf8, 0x15, 0xb4, 0x0b, 0xd7, 0x1c, 0x1f, 0x65, 0x79, 0x5b, 0x8b, 0x45, 0x7f, 0xbf, 0x14, 0x97,
	0x62, 0x52, 0xa3, 0x7f, 0x3f, 0xcf, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x43, 0x6a, 0x61, 0xef,
	0x24, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogicExtClient is the client API for LogicExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicExtClient interface {
	// 注册设备
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
	// 发送消息
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 添加好友
	AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error)
	// 同意添加好友
	AgreeAddFriend(ctx context.Context, in *AgreeAddFriendReq, opts ...grpc.CallOption) (*AgreeAddFriendResp, error)
	// 获取好友列表
	GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error)
	// 创建群组
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	// 更新群组
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error)
	// 获取群组信息
	GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error)
	// 获取用户加入的所有群组
	GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
	// 添加群组成员
	AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberResp, error)
	// 更新群组成员信息
	UpdateGroupMember(ctx context.Context, in *UpdateGroupMemberReq, opts ...grpc.CallOption) (*UpdateGroupMemberResp, error)
	// 添加群组成员
	DeleteGroupMember(ctx context.Context, in *DeleteGroupMemberReq, opts ...grpc.CallOption) (*DeleteGroupMemberResp, error)
	// 获取群组成员
	GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error)
}

type logicExtClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicExtClient(cc grpc.ClientConnInterface) LogicExtClient {
	return &logicExtClient{cc}
}

func (c *logicExtClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error) {
	out := new(AddFriendResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/AddFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) AgreeAddFriend(ctx context.Context, in *AgreeAddFriendReq, opts ...grpc.CallOption) (*AgreeAddFriendResp, error) {
	out := new(AgreeAddFriendResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/AgreeAddFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error) {
	out := new(GetFriendsResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/GetFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error) {
	out := new(UpdateGroupResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error) {
	out := new(GetGroupResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	out := new(GetUserGroupsResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/GetUserGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberResp, error) {
	out := new(AddGroupMemberResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/AddGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) UpdateGroupMember(ctx context.Context, in *UpdateGroupMemberReq, opts ...grpc.CallOption) (*UpdateGroupMemberResp, error) {
	out := new(UpdateGroupMemberResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/UpdateGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) DeleteGroupMember(ctx context.Context, in *DeleteGroupMemberReq, opts ...grpc.CallOption) (*DeleteGroupMemberResp, error) {
	out := new(DeleteGroupMemberResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/DeleteGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error) {
	out := new(GetGroupMembersResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/GetGroupMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicExtServer is the server API for LogicExt service.
type LogicExtServer interface {
	// 注册设备
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
	// 发送消息
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// 添加好友
	AddFriend(context.Context, *AddFriendReq) (*AddFriendResp, error)
	// 同意添加好友
	AgreeAddFriend(context.Context, *AgreeAddFriendReq) (*AgreeAddFriendResp, error)
	// 获取好友列表
	GetFriends(context.Context, *GetFriendsReq) (*GetFriendsResp, error)
	// 创建群组
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	// 更新群组
	UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupResp, error)
	// 获取群组信息
	GetGroup(context.Context, *GetGroupReq) (*GetGroupResp, error)
	// 获取用户加入的所有群组
	GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error)
	// 添加群组成员
	AddGroupMember(context.Context, *AddGroupMemberReq) (*AddGroupMemberResp, error)
	// 更新群组成员信息
	UpdateGroupMember(context.Context, *UpdateGroupMemberReq) (*UpdateGroupMemberResp, error)
	// 添加群组成员
	DeleteGroupMember(context.Context, *DeleteGroupMemberReq) (*DeleteGroupMemberResp, error)
	// 获取群组成员
	GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersResp, error)
}

// UnimplementedLogicExtServer can be embedded to have forward compatible implementations.
type UnimplementedLogicExtServer struct {
}

func (*UnimplementedLogicExtServer) RegisterDevice(ctx context.Context, req *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (*UnimplementedLogicExtServer) SendMessage(ctx context.Context, req *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedLogicExtServer) AddFriend(ctx context.Context, req *AddFriendReq) (*AddFriendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFriend not implemented")
}
func (*UnimplementedLogicExtServer) AgreeAddFriend(ctx context.Context, req *AgreeAddFriendReq) (*AgreeAddFriendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgreeAddFriend not implemented")
}
func (*UnimplementedLogicExtServer) GetFriends(ctx context.Context, req *GetFriendsReq) (*GetFriendsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriends not implemented")
}
func (*UnimplementedLogicExtServer) CreateGroup(ctx context.Context, req *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedLogicExtServer) UpdateGroup(ctx context.Context, req *UpdateGroupReq) (*UpdateGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (*UnimplementedLogicExtServer) GetGroup(ctx context.Context, req *GetGroupReq) (*GetGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedLogicExtServer) GetUserGroups(ctx context.Context, req *GetUserGroupsReq) (*GetUserGroupsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (*UnimplementedLogicExtServer) AddGroupMember(ctx context.Context, req *AddGroupMemberReq) (*AddGroupMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroupMember not implemented")
}
func (*UnimplementedLogicExtServer) UpdateGroupMember(ctx context.Context, req *UpdateGroupMemberReq) (*UpdateGroupMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupMember not implemented")
}
func (*UnimplementedLogicExtServer) DeleteGroupMember(ctx context.Context, req *DeleteGroupMemberReq) (*DeleteGroupMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroupMember not implemented")
}
func (*UnimplementedLogicExtServer) GetGroupMembers(ctx context.Context, req *GetGroupMembersReq) (*GetGroupMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMembers not implemented")
}

func RegisterLogicExtServer(s *grpc.Server, srv LogicExtServer) {
	s.RegisterService(&_LogicExt_serviceDesc, srv)
}

func _LogicExt_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).AddFriend(ctx, req.(*AddFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_AgreeAddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgreeAddFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).AgreeAddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/AgreeAddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).AgreeAddFriend(ctx, req.(*AgreeAddFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/GetFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).GetFriends(ctx, req.(*GetFriendsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).GetGroup(ctx, req.(*GetGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/GetUserGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).GetUserGroups(ctx, req.(*GetUserGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_AddGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).AddGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/AddGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).AddGroupMember(ctx, req.(*AddGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_UpdateGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).UpdateGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/UpdateGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).UpdateGroupMember(ctx, req.(*UpdateGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_DeleteGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).DeleteGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/DeleteGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).DeleteGroupMember(ctx, req.(*DeleteGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/GetGroupMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).GetGroupMembers(ctx, req.(*GetGroupMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogicExt",
	HandlerType: (*LogicExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _LogicExt_RegisterDevice_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _LogicExt_SendMessage_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _LogicExt_AddFriend_Handler,
		},
		{
			MethodName: "AgreeAddFriend",
			Handler:    _LogicExt_AgreeAddFriend_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _LogicExt_GetFriends_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _LogicExt_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _LogicExt_UpdateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _LogicExt_GetGroup_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _LogicExt_GetUserGroups_Handler,
		},
		{
			MethodName: "AddGroupMember",
			Handler:    _LogicExt_AddGroupMember_Handler,
		},
		{
			MethodName: "UpdateGroupMember",
			Handler:    _LogicExt_UpdateGroupMember_Handler,
		},
		{
			MethodName: "DeleteGroupMember",
			Handler:    _LogicExt_DeleteGroupMember_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _LogicExt_GetGroupMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.ext.proto",
}
