// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.ext.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterDeviceReq struct {
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemVersion        string   `protobuf:"bytes,5,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	SdkVersion           string   `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceReq) Reset()         { *m = RegisterDeviceReq{} }
func (m *RegisterDeviceReq) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceReq) ProtoMessage()    {}
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{0}
}

func (m *RegisterDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceReq.Unmarshal(m, b)
}
func (m *RegisterDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceReq.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceReq.Merge(m, src)
}
func (m *RegisterDeviceReq) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceReq.Size(m)
}
func (m *RegisterDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceReq proto.InternalMessageInfo

func (m *RegisterDeviceReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegisterDeviceReq) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *RegisterDeviceReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *RegisterDeviceReq) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *RegisterDeviceReq) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

type RegisterDeviceResp struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceResp) Reset()         { *m = RegisterDeviceResp{} }
func (m *RegisterDeviceResp) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceResp) ProtoMessage()    {}
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{1}
}

func (m *RegisterDeviceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceResp.Unmarshal(m, b)
}
func (m *RegisterDeviceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceResp.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceResp.Merge(m, src)
}
func (m *RegisterDeviceResp) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceResp.Size(m)
}
func (m *RegisterDeviceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceResp proto.InternalMessageInfo

func (m *RegisterDeviceResp) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type SendMessageReq struct {
	MessageId            string       `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceiverType         ReceiverType `protobuf:"varint,2,opt,name=receiver_type,json=receiverType,proto3,enum=pb.ReceiverType" json:"receiver_type,omitempty"`
	ReceiverId           int64        `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ToUserIds            []int64      `protobuf:"varint,4,rep,packed,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`
	MessageBody          *MessageBody `protobuf:"bytes,5,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	SendTime             int64        `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	IsPersist            bool         `protobuf:"varint,7,opt,name=is_persist,json=isPersist,proto3" json:"is_persist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{2}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SendMessageReq) GetReceiverType() ReceiverType {
	if m != nil {
		return m.ReceiverType
	}
	return ReceiverType_RT_UNKNOWN
}

func (m *SendMessageReq) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *SendMessageReq) GetToUserIds() []int64 {
	if m != nil {
		return m.ToUserIds
	}
	return nil
}

func (m *SendMessageReq) GetMessageBody() *MessageBody {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func (m *SendMessageReq) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *SendMessageReq) GetIsPersist() bool {
	if m != nil {
		return m.IsPersist
	}
	return false
}

type SendMessageResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{3}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

type Group struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	UserMum              int32    `protobuf:"varint,4,opt,name=user_mum,json=userMum,proto3" json:"user_mum,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Extra                string   `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	CreateTime           int64    `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{4}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Group) GetUserMum() int32 {
	if m != nil {
		return m.UserMum
	}
	return 0
}

func (m *Group) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Group) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *Group) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Group) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type CreateGroupReq struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReq) Reset()         { *m = CreateGroupReq{} }
func (m *CreateGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReq) ProtoMessage()    {}
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{5}
}

func (m *CreateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReq.Unmarshal(m, b)
}
func (m *CreateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReq.Merge(m, src)
}
func (m *CreateGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReq.Size(m)
}
func (m *CreateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReq proto.InternalMessageInfo

func (m *CreateGroupReq) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type CreateGroupResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResp) Reset()         { *m = CreateGroupResp{} }
func (m *CreateGroupResp) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResp) ProtoMessage()    {}
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{6}
}

func (m *CreateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResp.Unmarshal(m, b)
}
func (m *CreateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResp.Marshal(b, m, deterministic)
}
func (m *CreateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResp.Merge(m, src)
}
func (m *CreateGroupResp) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResp.Size(m)
}
func (m *CreateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResp proto.InternalMessageInfo

type UpdateGroupReq struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupReq) Reset()         { *m = UpdateGroupReq{} }
func (m *UpdateGroupReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupReq) ProtoMessage()    {}
func (*UpdateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{7}
}

func (m *UpdateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupReq.Unmarshal(m, b)
}
func (m *UpdateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupReq.Merge(m, src)
}
func (m *UpdateGroupReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupReq.Size(m)
}
func (m *UpdateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupReq proto.InternalMessageInfo

func (m *UpdateGroupReq) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type UpdateGroupResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResp) Reset()         { *m = UpdateGroupResp{} }
func (m *UpdateGroupResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResp) ProtoMessage()    {}
func (*UpdateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{8}
}

func (m *UpdateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResp.Unmarshal(m, b)
}
func (m *UpdateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResp.Merge(m, src)
}
func (m *UpdateGroupResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResp.Size(m)
}
func (m *UpdateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResp proto.InternalMessageInfo

type GetGroupReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupReq) Reset()         { *m = GetGroupReq{} }
func (m *GetGroupReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupReq) ProtoMessage()    {}
func (*GetGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{9}
}

func (m *GetGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupReq.Unmarshal(m, b)
}
func (m *GetGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupReq.Marshal(b, m, deterministic)
}
func (m *GetGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupReq.Merge(m, src)
}
func (m *GetGroupReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupReq.Size(m)
}
func (m *GetGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupReq proto.InternalMessageInfo

func (m *GetGroupReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GetGroupResp struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResp) Reset()         { *m = GetGroupResp{} }
func (m *GetGroupResp) String() string { return proto.CompactTextString(m) }
func (*GetGroupResp) ProtoMessage()    {}
func (*GetGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{10}
}

func (m *GetGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResp.Unmarshal(m, b)
}
func (m *GetGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResp.Marshal(b, m, deterministic)
}
func (m *GetGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResp.Merge(m, src)
}
func (m *GetGroupResp) XXX_Size() int {
	return xxx_messageInfo_GetGroupResp.Size(m)
}
func (m *GetGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResp proto.InternalMessageInfo

func (m *GetGroupResp) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GetUserGroupsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserGroupsReq) Reset()         { *m = GetUserGroupsReq{} }
func (m *GetUserGroupsReq) String() string { return proto.CompactTextString(m) }
func (*GetUserGroupsReq) ProtoMessage()    {}
func (*GetUserGroupsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{11}
}

func (m *GetUserGroupsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGroupsReq.Unmarshal(m, b)
}
func (m *GetUserGroupsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGroupsReq.Marshal(b, m, deterministic)
}
func (m *GetUserGroupsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGroupsReq.Merge(m, src)
}
func (m *GetUserGroupsReq) XXX_Size() int {
	return xxx_messageInfo_GetUserGroupsReq.Size(m)
}
func (m *GetUserGroupsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGroupsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGroupsReq proto.InternalMessageInfo

type GetUserGroupsResp struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserGroupsResp) Reset()         { *m = GetUserGroupsResp{} }
func (m *GetUserGroupsResp) String() string { return proto.CompactTextString(m) }
func (*GetUserGroupsResp) ProtoMessage()    {}
func (*GetUserGroupsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{12}
}

func (m *GetUserGroupsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGroupsResp.Unmarshal(m, b)
}
func (m *GetUserGroupsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGroupsResp.Marshal(b, m, deterministic)
}
func (m *GetUserGroupsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGroupsResp.Merge(m, src)
}
func (m *GetUserGroupsResp) XXX_Size() int {
	return xxx_messageInfo_GetUserGroupsResp.Size(m)
}
func (m *GetUserGroupsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGroupsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGroupsResp proto.InternalMessageInfo

func (m *GetUserGroupsResp) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

// 群组用户
type GroupUser struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupUser) Reset()         { *m = GroupUser{} }
func (m *GroupUser) String() string { return proto.CompactTextString(m) }
func (*GroupUser) ProtoMessage()    {}
func (*GroupUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{13}
}

func (m *GroupUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupUser.Unmarshal(m, b)
}
func (m *GroupUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupUser.Marshal(b, m, deterministic)
}
func (m *GroupUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupUser.Merge(m, src)
}
func (m *GroupUser) XXX_Size() int {
	return xxx_messageInfo_GroupUser.Size(m)
}
func (m *GroupUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupUser.DiscardUnknown(m)
}

var xxx_messageInfo_GroupUser proto.InternalMessageInfo

func (m *GroupUser) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupUser) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupUser) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *GroupUser) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type AddGroupMemberReq struct {
	GroupUser            *GroupUser `protobuf:"bytes,1,opt,name=group_user,json=groupUser,proto3" json:"group_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddGroupMemberReq) Reset()         { *m = AddGroupMemberReq{} }
func (m *AddGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberReq) ProtoMessage()    {}
func (*AddGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{14}
}

func (m *AddGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberReq.Unmarshal(m, b)
}
func (m *AddGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberReq.Merge(m, src)
}
func (m *AddGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberReq.Size(m)
}
func (m *AddGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberReq proto.InternalMessageInfo

func (m *AddGroupMemberReq) GetGroupUser() *GroupUser {
	if m != nil {
		return m.GroupUser
	}
	return nil
}

type AddGroupMemberResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberResp) Reset()         { *m = AddGroupMemberResp{} }
func (m *AddGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberResp) ProtoMessage()    {}
func (*AddGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{15}
}

func (m *AddGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberResp.Unmarshal(m, b)
}
func (m *AddGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberResp.Merge(m, src)
}
func (m *AddGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberResp.Size(m)
}
func (m *AddGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberResp proto.InternalMessageInfo

type UpdateGroupMemberReq struct {
	GroupUser            *GroupUser `protobuf:"bytes,1,opt,name=group_user,json=groupUser,proto3" json:"group_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateGroupMemberReq) Reset()         { *m = UpdateGroupMemberReq{} }
func (m *UpdateGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMemberReq) ProtoMessage()    {}
func (*UpdateGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{16}
}

func (m *UpdateGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMemberReq.Unmarshal(m, b)
}
func (m *UpdateGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMemberReq.Merge(m, src)
}
func (m *UpdateGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMemberReq.Size(m)
}
func (m *UpdateGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMemberReq proto.InternalMessageInfo

func (m *UpdateGroupMemberReq) GetGroupUser() *GroupUser {
	if m != nil {
		return m.GroupUser
	}
	return nil
}

type UpdateGroupMemberResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupMemberResp) Reset()         { *m = UpdateGroupMemberResp{} }
func (m *UpdateGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupMemberResp) ProtoMessage()    {}
func (*UpdateGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{17}
}

func (m *UpdateGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupMemberResp.Unmarshal(m, b)
}
func (m *UpdateGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupMemberResp.Merge(m, src)
}
func (m *UpdateGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupMemberResp.Size(m)
}
func (m *UpdateGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupMemberResp proto.InternalMessageInfo

type DeleteGroupMemberReq struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupMemberReq) Reset()         { *m = DeleteGroupMemberReq{} }
func (m *DeleteGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupMemberReq) ProtoMessage()    {}
func (*DeleteGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{18}
}

func (m *DeleteGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupMemberReq.Unmarshal(m, b)
}
func (m *DeleteGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *DeleteGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupMemberReq.Merge(m, src)
}
func (m *DeleteGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupMemberReq.Size(m)
}
func (m *DeleteGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupMemberReq proto.InternalMessageInfo

func (m *DeleteGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *DeleteGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteGroupMemberResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupMemberResp) Reset()         { *m = DeleteGroupMemberResp{} }
func (m *DeleteGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupMemberResp) ProtoMessage()    {}
func (*DeleteGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5bf3fa139aedf16, []int{19}
}

func (m *DeleteGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupMemberResp.Unmarshal(m, b)
}
func (m *DeleteGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *DeleteGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupMemberResp.Merge(m, src)
}
func (m *DeleteGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupMemberResp.Size(m)
}
func (m *DeleteGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupMemberResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterDeviceReq)(nil), "pb.RegisterDeviceReq")
	proto.RegisterType((*RegisterDeviceResp)(nil), "pb.RegisterDeviceResp")
	proto.RegisterType((*SendMessageReq)(nil), "pb.SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "pb.SendMessageResp")
	proto.RegisterType((*Group)(nil), "pb.Group")
	proto.RegisterType((*CreateGroupReq)(nil), "pb.CreateGroupReq")
	proto.RegisterType((*CreateGroupResp)(nil), "pb.CreateGroupResp")
	proto.RegisterType((*UpdateGroupReq)(nil), "pb.UpdateGroupReq")
	proto.RegisterType((*UpdateGroupResp)(nil), "pb.UpdateGroupResp")
	proto.RegisterType((*GetGroupReq)(nil), "pb.GetGroupReq")
	proto.RegisterType((*GetGroupResp)(nil), "pb.GetGroupResp")
	proto.RegisterType((*GetUserGroupsReq)(nil), "pb.GetUserGroupsReq")
	proto.RegisterType((*GetUserGroupsResp)(nil), "pb.GetUserGroupsResp")
	proto.RegisterType((*GroupUser)(nil), "pb.GroupUser")
	proto.RegisterType((*AddGroupMemberReq)(nil), "pb.AddGroupMemberReq")
	proto.RegisterType((*AddGroupMemberResp)(nil), "pb.AddGroupMemberResp")
	proto.RegisterType((*UpdateGroupMemberReq)(nil), "pb.UpdateGroupMemberReq")
	proto.RegisterType((*UpdateGroupMemberResp)(nil), "pb.UpdateGroupMemberResp")
	proto.RegisterType((*DeleteGroupMemberReq)(nil), "pb.DeleteGroupMemberReq")
	proto.RegisterType((*DeleteGroupMemberResp)(nil), "pb.DeleteGroupMemberResp")
}

func init() { proto.RegisterFile("logic.ext.proto", fileDescriptor_f5bf3fa139aedf16) }

var fileDescriptor_f5bf3fa139aedf16 = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0x13, 0x3d,
	0x10, 0xd5, 0x76, 0xf3, 0xb7, 0xb3, 0x49, 0xda, 0xf8, 0x4b, 0xbf, 0x6e, 0x83, 0xa0, 0xc1, 0x12,
	0x52, 0x2e, 0x20, 0xa8, 0x41, 0xf4, 0x0a, 0x09, 0x15, 0x8a, 0x4a, 0x10, 0x95, 0x90, 0x69, 0xb9,
	0x8d, 0x92, 0xd8, 0x8a, 0x56, 0xcd, 0x66, 0xdd, 0xb5, 0x53, 0x35, 0x4f, 0xc2, 0x05, 0xcf, 0xc1,
	0x03, 0xf1, 0x26, 0xc8, 0x9e, 0xcd, 0xcf, 0x26, 0x29, 0x88, 0xde, 0xed, 0x1c, 0xcf, 0x1c, 0x7b,
	0x8e, 0x8f, 0x67, 0x61, 0x77, 0x1c, 0x8f, 0xc2, 0x61, 0x5b, 0xdc, 0xe9, 0xb6, 0x4c, 0x62, 0x1d,
	0x93, 0x1d, 0x39, 0x68, 0x78, 0x7a, 0x28, 0x31, 0xa4, 0x3f, 0x1c, 0xa8, 0x31, 0x31, 0x0a, 0x95,
	0x16, 0xc9, 0x99, 0xb8, 0x0d, 0x87, 0x82, 0x89, 0x1b, 0x42, 0x20, 0xa7, 0x67, 0x52, 0x04, 0x3b,
	0x4d, 0xa7, 0x95, 0x67, 0xf6, 0x9b, 0xd4, 0x21, 0x3f, 0x48, 0xfa, 0x13, 0x1e, 0xb8, 0x4d, 0xa7,
	0xe5, 0x31, 0x0c, 0x0c, 0x1a, 0xc5, 0x5c, 0x8c, 0x83, 0x1c, 0xa2, 0x36, 0x20, 0xcf, 0xa0, 0xaa,
	0x66, 0x4a, 0x8b, 0xa8, 0x77, 0x2b, 0x12, 0x15, 0xc6, 0x93, 0x20, 0x6f, 0x97, 0x2b, 0x88, 0x7e,
	0x43, 0x90, 0x1c, 0x81, 0xaf, 0xf8, 0xf5, 0x22, 0xa7, 0x60, 0x73, 0x40, 0xf1, 0xeb, 0x34, 0x81,
	0x1e, 0x03, 0x59, 0x3f, 0x9c, 0x92, 0xe4, 0x11, 0x78, 0xdc, 0x46, 0xbd, 0x90, 0x07, 0x4e, 0xd3,
	0x69, 0xb9, 0xac, 0x84, 0x40, 0x97, 0xd3, 0xef, 0x3b, 0x50, 0xfd, 0x2a, 0x26, 0xfc, 0x42, 0x28,
	0xd5, 0x1f, 0xd9, 0x6e, 0x1e, 0x03, 0x44, 0x18, 0xcd, 0x0b, 0x3c, 0xe6, 0xa5, 0x48, 0x97, 0x93,
	0xd7, 0x50, 0x49, 0xc4, 0x50, 0x84, 0xb7, 0x22, 0xe9, 0x2d, 0xba, 0xae, 0x76, 0xf6, 0xda, 0x72,
	0xd0, 0x66, 0xe9, 0xc2, 0xe5, 0x4c, 0x0a, 0x56, 0x4e, 0x56, 0x22, 0x73, 0xf8, 0x45, 0x59, 0x88,
	0xaa, 0xb8, 0x0c, 0xe6, 0x50, 0x97, 0x93, 0x27, 0xe0, 0xeb, 0xb8, 0x37, 0x55, 0x76, 0x5d, 0x05,
	0xb9, 0xa6, 0xdb, 0x72, 0x99, 0xa7, 0xe3, 0x2b, 0x65, 0x96, 0x15, 0xe9, 0x40, 0x79, 0x7e, 0xac,
	0x41, 0xcc, 0x67, 0x56, 0x22, 0xbf, 0xb3, 0x6b, 0xb6, 0x4d, 0x0f, 0xff, 0x2e, 0xe6, 0x33, 0xe6,
	0x47, 0xcb, 0xc0, 0xb4, 0xae, 0xc4, 0x84, 0xf7, 0x74, 0x18, 0x09, 0xab, 0x97, 0xcb, 0x4a, 0x06,
	0xb8, 0x0c, 0x23, 0x61, 0xfa, 0x0c, 0x55, 0x4f, 0x1a, 0xed, 0x94, 0x0e, 0x8a, 0x4d, 0xa7, 0x55,
	0x62, 0x5e, 0xa8, 0xbe, 0x20, 0x40, 0x6b, 0xb0, 0x9b, 0x11, 0x46, 0x49, 0xfa, 0xcb, 0x81, 0xfc,
	0x79, 0x12, 0x4f, 0x25, 0x39, 0x84, 0xd2, 0xc8, 0x7c, 0x2c, 0x25, 0x2d, 0xda, 0xb8, 0xcb, 0x8d,
	0x19, 0x26, 0xfd, 0x08, 0x65, 0xf1, 0x98, 0xfd, 0x26, 0x14, 0xca, 0xe1, 0x44, 0x27, 0x31, 0x9f,
	0x0e, 0xb5, 0xb9, 0x3a, 0xf4, 0x44, 0x06, 0x33, 0x94, 0xb6, 0xf9, 0x68, 0x1a, 0x59, 0x77, 0xe4,
	0x59, 0xd1, 0xc4, 0x17, 0xd3, 0x68, 0xe1, 0xaf, 0x7c, 0xd6, 0x5f, 0xe2, 0x4e, 0x27, 0xfd, 0xd4,
	0x06, 0x18, 0x18, 0x95, 0x87, 0x89, 0xe8, 0x6b, 0x81, 0x2d, 0x17, 0x51, 0x65, 0x84, 0x6c, 0xd3,
	0x47, 0xe0, 0x4f, 0x25, 0x5f, 0x24, 0x94, 0x30, 0x01, 0x21, 0x93, 0x40, 0x8f, 0xa1, 0xfa, 0xde,
	0xa6, 0xdb, 0x46, 0x8d, 0x1f, 0x8e, 0x20, 0x6f, 0x7b, 0xb3, 0x8d, 0xfa, 0x1d, 0xcf, 0x28, 0x8e,
	0x8b, 0x88, 0x1b, 0xa5, 0x32, 0x25, 0x4a, 0x1a, 0x96, 0x2b, 0xcb, 0xf9, 0x4f, 0x2c, 0x99, 0x12,
	0x25, 0x69, 0x0b, 0xfc, 0x73, 0xa1, 0x17, 0x14, 0xf7, 0x8b, 0x4e, 0x5f, 0x42, 0x79, 0x99, 0xa9,
	0xe4, 0xdf, 0x77, 0x23, 0xb0, 0x77, 0x2e, 0xb4, 0xf1, 0x96, 0x85, 0x15, 0x13, 0x37, 0xf4, 0x04,
	0x6a, 0x6b, 0x98, 0x92, 0xe4, 0x29, 0x14, 0x6c, 0x85, 0x0a, 0x9c, 0xa6, 0x9b, 0xa5, 0x4a, 0x17,
	0xe8, 0x35, 0x78, 0x16, 0x30, 0x95, 0x7f, 0x72, 0xc6, 0x01, 0x14, 0x53, 0x7b, 0x5b, 0x73, 0xb8,
	0xac, 0x30, 0xb5, 0xde, 0x36, 0x77, 0x39, 0xee, 0x0f, 0xc4, 0x78, 0x3e, 0x2b, 0x6c, 0xb0, 0xbc,
	0xe1, 0xdc, 0xca, 0x0d, 0xd3, 0x53, 0xa8, 0x9d, 0x72, 0x6e, 0xf7, 0xbb, 0x10, 0xd1, 0x40, 0x24,
	0x46, 0x99, 0xe7, 0x00, 0xb8, 0xa9, 0x21, 0x4c, 0x7b, 0xae, 0x2c, 0x0e, 0x6a, 0xce, 0xc5, 0xbc,
	0xd1, 0xfc, 0x93, 0xd6, 0x81, 0xac, 0x53, 0x28, 0x49, 0xcf, 0xa0, 0xbe, 0xa2, 0xff, 0x43, 0xb9,
	0x0f, 0x60, 0x7f, 0x0b, 0x8b, 0x92, 0xf4, 0x13, 0xd4, 0xcf, 0xc4, 0x58, 0x6c, 0xd0, 0x3f, 0x40,
	0x2f, 0xb3, 0xc9, 0x16, 0x2e, 0x25, 0x3b, 0x3f, 0x73, 0x50, 0xfa, 0x6c, 0x26, 0xf8, 0x87, 0x3b,
	0x4d, 0xde, 0x42, 0x35, 0x3b, 0x0d, 0xc9, 0x3e, 0xce, 0xa8, 0xb5, 0xf1, 0xdd, 0xf8, 0x7f, 0x1b,
	0xac, 0x24, 0x39, 0x01, 0x7f, 0x65, 0x02, 0x10, 0x62, 0xd2, 0xb2, 0xb3, 0xb2, 0xf1, 0xdf, 0x06,
	0x86, 0x75, 0x2b, 0xef, 0x01, 0xeb, 0xb2, 0x6f, 0x0a, 0xeb, 0xd6, 0x1e, 0x8d, 0xa9, 0x5b, 0xd1,
	0x0e, 0xeb, 0xb2, 0xaf, 0x08, 0xeb, 0xd6, 0x9e, 0x09, 0x79, 0x01, 0xa5, 0xb9, 0xf9, 0x89, 0x9d,
	0x87, 0x2b, 0x8f, 0xa6, 0xb1, 0x97, 0x05, 0x94, 0x24, 0x6f, 0xa0, 0x92, 0xb1, 0x39, 0xa9, 0xa7,
	0x29, 0x99, 0xd7, 0xd0, 0xd8, 0xdf, 0x82, 0x2a, 0x69, 0x54, 0xcd, 0x9a, 0x07, 0x55, 0xdd, 0xf0,
	0x24, 0xaa, 0xba, 0xe9, 0x33, 0xf2, 0x11, 0x6a, 0x1b, 0x0e, 0x21, 0xc1, 0x5a, 0x5f, 0x4b, 0x9a,
	0xc3, 0x7b, 0x56, 0x90, 0x69, 0xc3, 0x06, 0xc8, 0xb4, 0xcd, 0x69, 0xc8, 0xb4, 0xd5, 0x37, 0x83,
	0x82, 0xfd, 0xbb, 0xbf, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xb3, 0x04, 0x67, 0xff, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogicExtClient is the client API for LogicExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicExtClient interface {
	// 注册设备
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
	// 发送消息
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 创建群组
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	// 更新群组
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error)
	// 获取群组信息
	GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error)
	// 获取用户加入的所有群组
	GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
	// 添加群组成员
	AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberResp, error)
	// 更新群组成员信息
	UpdateGroupMember(ctx context.Context, in *UpdateGroupMemberReq, opts ...grpc.CallOption) (*UpdateGroupMemberResp, error)
	// 添加群组成员
	DeleteGroupMember(ctx context.Context, in *DeleteGroupMemberReq, opts ...grpc.CallOption) (*DeleteGroupMemberResp, error)
}

type logicExtClient struct {
	cc *grpc.ClientConn
}

func NewLogicExtClient(cc *grpc.ClientConn) LogicExtClient {
	return &logicExtClient{cc}
}

func (c *logicExtClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error) {
	out := new(UpdateGroupResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error) {
	out := new(GetGroupResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	out := new(GetUserGroupsResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/GetUserGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberResp, error) {
	out := new(AddGroupMemberResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/AddGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) UpdateGroupMember(ctx context.Context, in *UpdateGroupMemberReq, opts ...grpc.CallOption) (*UpdateGroupMemberResp, error) {
	out := new(UpdateGroupMemberResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/UpdateGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicExtClient) DeleteGroupMember(ctx context.Context, in *DeleteGroupMemberReq, opts ...grpc.CallOption) (*DeleteGroupMemberResp, error) {
	out := new(DeleteGroupMemberResp)
	err := c.cc.Invoke(ctx, "/pb.LogicExt/DeleteGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicExtServer is the server API for LogicExt service.
type LogicExtServer interface {
	// 注册设备
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
	// 发送消息
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// 创建群组
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	// 更新群组
	UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupResp, error)
	// 获取群组信息
	GetGroup(context.Context, *GetGroupReq) (*GetGroupResp, error)
	// 获取用户加入的所有群组
	GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error)
	// 添加群组成员
	AddGroupMember(context.Context, *AddGroupMemberReq) (*AddGroupMemberResp, error)
	// 更新群组成员信息
	UpdateGroupMember(context.Context, *UpdateGroupMemberReq) (*UpdateGroupMemberResp, error)
	// 添加群组成员
	DeleteGroupMember(context.Context, *DeleteGroupMemberReq) (*DeleteGroupMemberResp, error)
}

// UnimplementedLogicExtServer can be embedded to have forward compatible implementations.
type UnimplementedLogicExtServer struct {
}

func (*UnimplementedLogicExtServer) RegisterDevice(ctx context.Context, req *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (*UnimplementedLogicExtServer) SendMessage(ctx context.Context, req *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedLogicExtServer) CreateGroup(ctx context.Context, req *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedLogicExtServer) UpdateGroup(ctx context.Context, req *UpdateGroupReq) (*UpdateGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (*UnimplementedLogicExtServer) GetGroup(ctx context.Context, req *GetGroupReq) (*GetGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedLogicExtServer) GetUserGroups(ctx context.Context, req *GetUserGroupsReq) (*GetUserGroupsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (*UnimplementedLogicExtServer) AddGroupMember(ctx context.Context, req *AddGroupMemberReq) (*AddGroupMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroupMember not implemented")
}
func (*UnimplementedLogicExtServer) UpdateGroupMember(ctx context.Context, req *UpdateGroupMemberReq) (*UpdateGroupMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupMember not implemented")
}
func (*UnimplementedLogicExtServer) DeleteGroupMember(ctx context.Context, req *DeleteGroupMemberReq) (*DeleteGroupMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroupMember not implemented")
}

func RegisterLogicExtServer(s *grpc.Server, srv LogicExtServer) {
	s.RegisterService(&_LogicExt_serviceDesc, srv)
}

func _LogicExt_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).GetGroup(ctx, req.(*GetGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/GetUserGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).GetUserGroups(ctx, req.(*GetUserGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_AddGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).AddGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/AddGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).AddGroupMember(ctx, req.(*AddGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_UpdateGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).UpdateGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/UpdateGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).UpdateGroupMember(ctx, req.(*UpdateGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicExt_DeleteGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicExtServer).DeleteGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicExt/DeleteGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicExtServer).DeleteGroupMember(ctx, req.(*DeleteGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogicExt",
	HandlerType: (*LogicExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _LogicExt_RegisterDevice_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _LogicExt_SendMessage_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _LogicExt_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _LogicExt_UpdateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _LogicExt_GetGroup_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _LogicExt_GetUserGroups_Handler,
		},
		{
			MethodName: "AddGroupMember",
			Handler:    _LogicExt_AddGroupMember_Handler,
		},
		{
			MethodName: "UpdateGroupMember",
			Handler:    _LogicExt_UpdateGroupMember_Handler,
		},
		{
			MethodName: "DeleteGroupMember",
			Handler:    _LogicExt_DeleteGroupMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.ext.proto",
}
