// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushCode int32

const (
	PushCode_PC_ADD_DEFAULT      PushCode = 0
	PushCode_PC_ADD_FRIEND       PushCode = 100
	PushCode_PC_AGREE_ADD_FRIEND PushCode = 101
	PushCode_PC_AGREE_ADD_GROUP  PushCode = 110
)

var PushCode_name = map[int32]string{
	0:   "PC_ADD_DEFAULT",
	100: "PC_ADD_FRIEND",
	101: "PC_AGREE_ADD_FRIEND",
	110: "PC_AGREE_ADD_GROUP",
}

var PushCode_value = map[string]int32{
	"PC_ADD_DEFAULT":      0,
	"PC_ADD_FRIEND":       100,
	"PC_AGREE_ADD_FRIEND": 101,
	"PC_AGREE_ADD_GROUP":  110,
}

func (x PushCode) String() string {
	return proto.EnumName(PushCode_name, int32(x))
}

func (PushCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{0}
}

// 推送码 PC_ADD_FRIEND = 100
type AddFriendPush struct {
	FriendId             int64    `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendPush) Reset()         { *m = AddFriendPush{} }
func (m *AddFriendPush) String() string { return proto.CompactTextString(m) }
func (*AddFriendPush) ProtoMessage()    {}
func (*AddFriendPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{0}
}

func (m *AddFriendPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendPush.Unmarshal(m, b)
}
func (m *AddFriendPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendPush.Marshal(b, m, deterministic)
}
func (m *AddFriendPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendPush.Merge(m, src)
}
func (m *AddFriendPush) XXX_Size() int {
	return xxx_messageInfo_AddFriendPush.Size(m)
}
func (m *AddFriendPush) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendPush.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendPush proto.InternalMessageInfo

func (m *AddFriendPush) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *AddFriendPush) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AddFriendPush) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *AddFriendPush) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// 推送码 PC_AGREE_ADD_FRIEND = 101
type AgreeAddFriendPush struct {
	FriendId             int64    `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeAddFriendPush) Reset()         { *m = AgreeAddFriendPush{} }
func (m *AgreeAddFriendPush) String() string { return proto.CompactTextString(m) }
func (*AgreeAddFriendPush) ProtoMessage()    {}
func (*AgreeAddFriendPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1}
}

func (m *AgreeAddFriendPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeAddFriendPush.Unmarshal(m, b)
}
func (m *AgreeAddFriendPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeAddFriendPush.Marshal(b, m, deterministic)
}
func (m *AgreeAddFriendPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeAddFriendPush.Merge(m, src)
}
func (m *AgreeAddFriendPush) XXX_Size() int {
	return xxx_messageInfo_AgreeAddFriendPush.Size(m)
}
func (m *AgreeAddFriendPush) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeAddFriendPush.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeAddFriendPush proto.InternalMessageInfo

func (m *AgreeAddFriendPush) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *AgreeAddFriendPush) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AgreeAddFriendPush) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.PushCode", PushCode_name, PushCode_value)
	proto.RegisterType((*AddFriendPush)(nil), "pb.AddFriendPush")
	proto.RegisterType((*AgreeAddFriendPush)(nil), "pb.AgreeAddFriendPush")
}

func init() { proto.RegisterFile("push.proto", fileDescriptor_d1e4bfd2e9d102bb) }

var fileDescriptor_d1e4bfd2e9d102bb = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0xd0, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x71, 0xbb, 0x89, 0xb4, 0x47, 0x26, 0xf5, 0x08, 0x5a, 0x14, 0xa1, 0xec, 0x6a, 0x78,
	0xe1, 0x8d, 0x4f, 0x50, 0xd6, 0x74, 0x0c, 0x44, 0x4b, 0xb0, 0xd7, 0x21, 0xdd, 0x89, 0x2e, 0x58,
	0x93, 0x90, 0xb6, 0xbe, 0x83, 0x6f, 0x2d, 0xcb, 0x44, 0xe6, 0x0b, 0x78, 0xf9, 0xfd, 0xfe, 0x10,
	0xc2, 0x01, 0x70, 0x63, 0xbf, 0xbd, 0x77, 0xde, 0x0e, 0x16, 0x27, 0xae, 0x9d, 0x7f, 0x45, 0x30,
	0x2b, 0x88, 0x2a, 0xaf, 0x95, 0xa1, 0x7a, 0xec, 0xb7, 0x78, 0x03, 0xc9, 0x6b, 0x58, 0x42, 0x53,
	0x16, 0xe5, 0xd1, 0x62, 0xca, 0xe3, 0x3d, 0xac, 0x09, 0xaf, 0x21, 0x36, 0x7a, 0xf3, 0x6e, 0xe4,
	0x87, 0xca, 0x26, 0x79, 0xb4, 0x48, 0xf8, 0xef, 0xc6, 0x5b, 0x00, 0xf9, 0x29, 0x07, 0xe9, 0xc5,
	0xe8, 0xbb, 0x6c, 0x1a, 0x6a, 0xb2, 0x97, 0xc6, 0x77, 0x98, 0xc3, 0x29, 0xa9, 0x7e, 0xe3, 0xb5,
	0x1b, 0xb4, 0x35, 0xd9, 0x71, 0xe8, 0x87, 0x34, 0xef, 0x00, 0x8b, 0x37, 0xaf, 0xd4, 0xbf, 0xfc,
	0xe7, 0xae, 0x85, 0x78, 0xf7, 0xfe, 0xd2, 0x92, 0x42, 0x84, 0xb3, 0x7a, 0x29, 0x8a, 0xb2, 0x14,
	0x25, 0xab, 0x8a, 0xe6, 0xf1, 0x25, 0x3d, 0xc2, 0x73, 0x98, 0xfd, 0x58, 0xc5, 0xd7, 0xec, 0xa9,
	0x4c, 0x09, 0xaf, 0xe0, 0x62, 0x47, 0x2b, 0xce, 0xd8, 0x61, 0x50, 0x78, 0x09, 0xf8, 0x27, 0xac,
	0xf8, 0x73, 0x53, 0xa7, 0xa6, 0x3d, 0x09, 0x87, 0x7e, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x79,
	0x10, 0x26, 0x46, 0x76, 0x01, 0x00, 0x00,
}
