// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.int.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *AuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{1}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

type User struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Extra                string   `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type AddUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{3}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AddUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResp) Reset()         { *m = AddUserResp{} }
func (m *AddUserResp) String() string { return proto.CompactTextString(m) }
func (*AddUserResp) ProtoMessage()    {}
func (*AddUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{4}
}

func (m *AddUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResp.Unmarshal(m, b)
}
func (m *AddUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResp.Marshal(b, m, deterministic)
}
func (m *AddUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResp.Merge(m, src)
}
func (m *AddUserResp) XXX_Size() int {
	return xxx_messageInfo_AddUserResp.Size(m)
}
func (m *AddUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResp proto.InternalMessageInfo

type GetUsersReq struct {
	UserIds              []int64  `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersReq) Reset()         { *m = GetUsersReq{} }
func (m *GetUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetUsersReq) ProtoMessage()    {}
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{5}
}

func (m *GetUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReq.Unmarshal(m, b)
}
func (m *GetUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReq.Marshal(b, m, deterministic)
}
func (m *GetUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReq.Merge(m, src)
}
func (m *GetUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetUsersReq.Size(m)
}
func (m *GetUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReq proto.InternalMessageInfo

func (m *GetUsersReq) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type GetUsersResp struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResp) Reset()         { *m = GetUsersResp{} }
func (m *GetUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetUsersResp) ProtoMessage()    {}
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{6}
}

func (m *GetUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResp.Unmarshal(m, b)
}
func (m *GetUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResp.Marshal(b, m, deterministic)
}
func (m *GetUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResp.Merge(m, src)
}
func (m *GetUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetUsersResp.Size(m)
}
func (m *GetUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResp proto.InternalMessageInfo

func (m *GetUsersResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthReq)(nil), "pb.AuthReq")
	proto.RegisterType((*AuthResp)(nil), "pb.AuthResp")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*AddUserReq)(nil), "pb.AddUserReq")
	proto.RegisterType((*AddUserResp)(nil), "pb.AddUserResp")
	proto.RegisterType((*GetUsersReq)(nil), "pb.GetUsersReq")
	proto.RegisterType((*GetUsersResp)(nil), "pb.GetUsersResp")
}

func init() { proto.RegisterFile("user.int.proto", fileDescriptor_a691eb292bdaab8c) }

var fileDescriptor_a691eb292bdaab8c = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x6e, 0xba, 0x40,
	0x14, 0xc5, 0x83, 0x80, 0xc0, 0xc5, 0xff, 0xbf, 0x66, 0xd2, 0xa4, 0xd4, 0x7e, 0xd9, 0x59, 0x91,
	0x26, 0x65, 0x61, 0x9f, 0xc0, 0x55, 0xe3, 0x96, 0xd4, 0x55, 0x17, 0x06, 0x9d, 0x9b, 0x94, 0xa8,
	0x38, 0x9d, 0x19, 0x8c, 0x0f, 0xd8, 0x07, 0x6b, 0xee, 0x8c, 0x45, 0xbb, 0xe8, 0x8e, 0x73, 0xce,
	0x8f, 0xfb, 0x05, 0xf0, 0xbf, 0xd5, 0xa8, 0x8a, 0xba, 0x31, 0x85, 0x54, 0x3b, 0xb3, 0x63, 0x3d,
	0xb9, 0xe4, 0x73, 0x88, 0xa6, 0xad, 0xf9, 0x28, 0xf1, 0x93, 0x5d, 0x41, 0x44, 0xc0, 0xa2, 0x16,
	0x99, 0x37, 0xf6, 0x72, 0xbf, 0xec, 0x93, 0x9c, 0x09, 0x76, 0x03, 0x89, 0xc0, 0x7d, 0xbd, 0x42,
	0x8a, 0x7a, 0x36, 0x8a, 0x9d, 0x31, 0x13, 0xec, 0x12, 0x42, 0xb3, 0x5b, 0x63, 0x93, 0xf9, 0x63,
	0x2f, 0x4f, 0x4a, 0x27, 0x38, 0x40, 0xec, 0xca, 0x6a, 0xc9, 0xbf, 0x3c, 0x08, 0xe6, 0x1a, 0xd5,
	0xdf, 0x0d, 0x46, 0x10, 0x37, 0xf5, 0x6a, 0xdd, 0x54, 0x5b, 0xb4, 0xf5, 0x93, 0xb2, 0xd3, 0x6c,
	0x08, 0xbe, 0xc6, 0x83, 0xad, 0x1e, 0x96, 0xf4, 0xc8, 0xee, 0x00, 0xaa, 0x7d, 0x65, 0x2a, 0xb5,
	0x68, 0xd5, 0x26, 0x0b, 0x2c, 0x9f, 0x38, 0x67, 0xae, 0x36, 0x34, 0x10, 0x1e, 0x8c, 0xaa, 0xb2,
	0xd0, 0x0d, 0x64, 0x05, 0x7b, 0x80, 0x74, 0xa5, 0xb0, 0x32, 0xb8, 0x30, 0xf5, 0x16, 0xb3, 0xbe,
	0xed, 0x0f, 0xce, 0x7a, 0xab, 0xb7, 0x48, 0x40, 0x2b, 0x45, 0x07, 0x44, 0x0e, 0x70, 0x16, 0x01,
	0xfc, 0x09, 0x60, 0x2a, 0x04, 0x2d, 0x42, 0xc7, 0xba, 0x85, 0x80, 0x86, 0xb7, 0x8b, 0xa4, 0x93,
	0xb8, 0x90, 0xcb, 0xc2, 0x46, 0xd6, 0xe5, 0xff, 0x20, 0xed, 0x58, 0x2d, 0x79, 0x0e, 0xe9, 0x2b,
	0x1a, 0x92, 0x9a, 0xde, 0xbd, 0x86, 0xf8, 0x78, 0x07, 0x9d, 0x79, 0x63, 0x3f, 0xf7, 0xcb, 0xc8,
	0x1d, 0x42, 0xf3, 0x02, 0x06, 0x27, 0x52, 0x4b, 0x76, 0x0f, 0x21, 0x45, 0x8e, 0x3b, 0xef, 0xe3,
	0xec, 0xc9, 0x3b, 0x44, 0x24, 0x67, 0x8d, 0x61, 0x8f, 0x10, 0xd0, 0xc9, 0x59, 0x4a, 0xcc, 0xf1,
	0x9b, 0x8e, 0x06, 0x27, 0xa1, 0x25, 0x7b, 0x86, 0xf8, 0xa7, 0x3a, 0xbb, 0xa0, 0xe4, 0x6c, 0xaa,
	0xd1, 0xf0, 0xb7, 0xa1, 0xe5, 0xb2, 0x6f, 0x7f, 0x93, 0x97, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb1, 0x20, 0x10, 0x52, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserIntClient is the client API for UserInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserIntClient interface {
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error)
}

type userIntClient struct {
	cc grpc.ClientConnInterface
}

func NewUserIntClient(cc grpc.ClientConnInterface) UserIntClient {
	return &userIntClient{cc}
}

func (c *userIntClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/pb.UserInt/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userIntClient) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error) {
	out := new(GetUsersResp)
	err := c.cc.Invoke(ctx, "/pb.UserInt/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIntServer is the server API for UserInt service.
type UserIntServer interface {
	Auth(context.Context, *AuthReq) (*AuthResp, error)
	GetUsers(context.Context, *GetUsersReq) (*GetUsersResp, error)
}

// UnimplementedUserIntServer can be embedded to have forward compatible implementations.
type UnimplementedUserIntServer struct {
}

func (*UnimplementedUserIntServer) Auth(ctx context.Context, req *AuthReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedUserIntServer) GetUsers(ctx context.Context, req *GetUsersReq) (*GetUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}

func RegisterUserIntServer(s *grpc.Server, srv UserIntServer) {
	s.RegisterService(&_UserInt_serviceDesc, srv)
}

func _UserInt_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserInt/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInt_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserInt/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).GetUsers(ctx, req.(*GetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserInt",
	HandlerType: (*UserIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _UserInt_Auth_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserInt_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.int.proto",
}
